using CommunityToolkit.Mvvm.Input;
using MarkdownMkII.Core.Text;
using MarkdownMkII.Services.Localization;

namespace MarkdownMkII.ViewModels;

public sealed record PaletteCommand(string Id, string Label, IRelayCommand Command, string? DefaultShortcut = null)
{
    public string? Shortcut => Services.ShortcutService.Effective(this);
    public string Category => CommandPresentation.Category(Id);
    public string Keywords => CommandPresentation.Keywords(Id);
    public bool IsGlobal => Id is "open" or "quickOpen" or "searchNotes" or "palette" or "lockNotes" or "unlockNotes" || Id.StartsWith("new", StringComparison.Ordinal);
}

public static class EditorPalette
{
    private static readonly System.Runtime.CompilerServices.ConditionalWeakTable<EditorViewModel, IReadOnlyList<PaletteCommand>> Cache = new();
    public static IReadOnlyList<PaletteCommand> Commands(EditorViewModel vm) => Cache.GetValue(vm, Create);
    private static IReadOnlyList<PaletteCommand> Create(EditorViewModel vm) =>
    [
        new("protectNote", Strings.T("SecurityProtect"), vm.ProtectNoteCommand),
        new("unprotectNote", Strings.T("SecurityUnprotect"), vm.RemoveNoteProtectionCommand),
        new("lockNotes", Strings.T("SecurityLockAll"), vm.LockNotesCommand),
        new("unlockNotes", Strings.T("SecurityUnlock"), vm.UnlockNotesCommand),
        new("replace", Strings.T("CmdReplace.Label"), vm.ShowReplaceCommand, "Ctrl+H"),
        new("refreshPreview", Strings.T("CmdRefreshPreview.Label"), vm.RefreshPreviewCommand, "F5"),
        new("toggleTask", Strings.T("CmdToggleTask.Label"), vm.ToggleTaskCommand, "Ctrl+Enter"),
        new("zoomIn", Strings.T("CmdZoomIn.Label"), vm.ZoomInCommand, "Ctrl+Plus"),
        new("zoomOut", Strings.T("CmdZoomOut.Label"), vm.ZoomOutCommand, "Ctrl+Minus"),
        new("inspector", Strings.T("WorkspaceInspector.Label"), vm.ToggleInspectorCommand),
        new("viewEditor", Strings.T("CmdViewEditor.Label"), new RelayCommand(() => vm.SetViewMode("Editor"))),
        new("viewPreview", Strings.T("CmdViewPreview.Label"), new RelayCommand(() => vm.SetViewMode("Preview"))),
        new("viewSplitVertical", Strings.T("CmdViewSplitVertical.Label"), new RelayCommand(() => vm.SetViewMode("SplitVertical"))),
        new("viewSplit", Strings.T("CmdViewSplit.Label"), new RelayCommand(() => vm.SetViewMode("Split"))),
        new("palette", Strings.T("ArchiveCommandSearch"), vm.ShowCommandPaletteCommand, "Ctrl+Shift+P"),
        new("close", Strings.T("ArchiveCloseEditor"), vm.CloseEditorCommand, "Ctrl+W"),
        new("exportMd", Strings.T("ArchiveExport"), vm.ExportMarkdownCommand),
        new("new", Strings.T("CmdNew.Label"), vm.NewDocumentCommand, "Ctrl+N"),
        new("newDaily", Strings.T("CmdNewDaily.Label"), vm.NewDailyCommand),
        new("newYesterday", Strings.T("CmdNewYesterday.Label"), vm.NewYesterdayCommand),
        new("newTomorrow", Strings.T("CmdNewTomorrow.Label"), vm.NewTomorrowCommand),
        new("newWeekly", Strings.T("CmdNewWeekly.Label"), vm.NewWeeklyCommand),
        new("newMonthly", Strings.T("CmdNewMonthly.Label"), vm.NewMonthlyCommand),
        new("newQuarterly", Strings.T("CmdNewQuarterly.Label"), vm.NewQuarterlyCommand),
        new("newYearly", Strings.T("CmdNewYearly.Label"), vm.NewYearlyCommand),
        new("newTemplate", Strings.T("CmdNewFromTemplate.Label"), vm.NewFromTemplateCommand),
        new("open", Strings.T("CmdOpen.Label"), vm.OpenCommand, "Ctrl+O"),
        new("quickOpen", Strings.T("CmdQuickOpen.Label"), vm.ShowQuickOpenCommand, "Ctrl+P"),
        new("searchNotes", Strings.T("CmdSearchNotes.Label"), new RelayCommand(() => (App.MainWindow as MainWindow)?.FocusNoteSearch()), "Ctrl+Shift+F"),
        new("goToHeading", Strings.T("CmdGoToHeading.Label"), vm.ShowGoToHeadingCommand, "Ctrl+Shift+O"),
        new("save", Strings.T("CmdSave.Label"), vm.SaveCommand, "Ctrl+S"),
        new("undo", Strings.T("CmdUndo.Label"), vm.UndoCommand, "Ctrl+Z"),
        new("redo", Strings.T("CmdRedo.Label"), vm.RedoCommand, "Ctrl+Y"),
        new("bold", Strings.T("CmdBold.Label"), vm.BoldCommand, "Ctrl+B"),
        new("italic", Strings.T("CmdItalic.Label"), vm.ItalicCommand, "Ctrl+I"),
        new("strike", Strings.T("CmdStrike.Label"), vm.StrikeCommand),
        new("highlight", Strings.T("CmdHighlight.Label"), vm.HighlightCommand),
        new("superscript", Strings.T("CmdSuperscript.Label"), vm.SuperscriptCommand),
        new("subscript", Strings.T("CmdSubscript.Label"), vm.SubscriptCommand),
        new("underline", Strings.T("CmdInserted.Label"), vm.InsertedCommand),
        new("code", Strings.T("CmdCode.Label"), vm.InlineCodeCommand),
        new("link", Strings.T("CmdLink.Label"), vm.LinkCommand, "Ctrl+K"),
        new("image", Strings.T("CmdImage.Label"), vm.ImageCommand),
        new("bullet", Strings.T("CmdBullet.Label"), vm.BulletListCommand),
        new("numbered", Strings.T("CmdNumbered.Label"), vm.NumberedListCommand),
        new("task", Strings.T("CmdTask.Label"), vm.TaskListCommand),
        new("checkTasks", Strings.T("CmdCheckTasks.Label"), vm.CheckTasksCommand),
        new("uncheckTasks", Strings.T("CmdUncheckTasks.Label"), vm.UncheckTasksCommand),
        new("quote", Strings.T("CmdQuote.Label"), vm.QuoteCommand),
        new("nestQuote", Strings.T("CmdNestQuote.Label"), vm.NestQuoteCommand),
        new("unnestQuote", Strings.T("CmdUnnestQuote.Label"), vm.UnnestQuoteCommand),
        new("table", Strings.T("CmdTable.Label"), vm.TableCommand),
        new("addTableRow", Strings.T("CmdAddTableRow.Label"), vm.AddTableRowCommand),
        new("duplicateTableRow", Strings.T("CmdDuplicateTableRow.Label"), vm.DuplicateTableRowCommand),
        new("deleteTableRow", Strings.T("CmdDeleteTableRow.Label"), vm.DeleteTableRowCommand),
        new("addTableColumn", Strings.T("CmdAddTableColumn.Label"), vm.AddTableColumnCommand),
        new("deleteTableColumn", Strings.T("CmdDeleteTableColumn.Label"), vm.DeleteTableColumnCommand),
        new("moveTableLeft", Strings.T("CmdMoveTableLeft.Label"), vm.MoveTableColumnLeftCommand),
        new("moveTableRight", Strings.T("CmdMoveTableRight.Label"), vm.MoveTableColumnRightCommand),
        new("duplicateTableColumn", Strings.T("CmdDuplicateTableColumn.Label"), vm.DuplicateTableColumnCommand),
        new("tableToList", Strings.T("CmdTableToList.Label"), vm.TableToListCommand),
        new("listToTable", Strings.T("CmdListToTable.Label"), vm.ListToTableCommand),
        new("moveTableRowUp", Strings.T("CmdMoveTableRowUp.Label"), vm.MoveTableRowUpCommand),
        new("moveTableRowDown", Strings.T("CmdMoveTableRowDown.Label"), vm.MoveTableRowDownCommand),
        new("copyTable", Strings.T("CmdCopyTable.Label"), vm.CopyTableCommand),
        new("copyTableTsv", Strings.T("CmdCopyTableTsv.Label"), vm.CopyTableTsvCommand),
        new("copyTableHtml", Strings.T("CmdCopyTableHtml.Label"), vm.CopyTableHtmlCommand),
        new("formatTable", Strings.T("CmdFormatTable.Label"), vm.FormatTableCommand),
        new("tableFromCsv", Strings.T("CmdTableFromCsv.Label"), vm.TableFromCsvCommand),
        new("alignLeft", Strings.T("CmdAlignLeft.Label"), vm.AlignTableLeftCommand),
        new("alignCenter", Strings.T("CmdAlignCenter.Label"), vm.AlignTableCenterCommand),
        new("alignRight", Strings.T("CmdAlignRight.Label"), vm.AlignTableRightCommand),
        new("sortTable", Strings.T("CmdSortTable.Label"), vm.SortTableCommand),
        new("sortTableDesc", Strings.T("CmdSortTableDesc.Label"), vm.SortTableDescendingCommand),
        new("transposeTable", Strings.T("CmdTransposeTable.Label"), vm.TransposeTableCommand),
        new("frontMatter", Strings.T("CmdFrontMatter.Label"), vm.FrontMatterCommand),
        new("stripFrontMatter", Strings.T("CmdStripFrontMatter.Label"), vm.StripFrontMatterCommand),
        new("fence", Strings.T("CmdFence.Label"), vm.CodeFenceCommand),
        new("rule", Strings.T("CmdRule.Label"), vm.HorizontalRuleCommand),
        new("definition", Strings.T("CmdDefinition.Label"), vm.DefinitionListCommand),
        new("find", Strings.T("CmdFind.Label"), vm.ToggleFindCommand, "Ctrl+F"),
        new("goToLine", Strings.T("GoToLine"), vm.GoToLineCommand, "Ctrl+G"),
        new("print", Strings.T("CmdPrint.Label"), vm.PrintCommand),
        new("export", Strings.T("CmdExport.Label"), vm.ExportHtmlCommand),
        new("h1", Strings.T("CmdH1.Label"), vm.Heading1Command, "Ctrl+1"),
        new("h2", Strings.T("CmdH2.Label"), vm.Heading2Command, "Ctrl+2"),
        new("h3", Strings.T("CmdH3.Label"), vm.Heading3Command, "Ctrl+3"),
        new("h4", Strings.T("EditorMenuHeading4"), vm.Heading4Command),
        new("h5", Strings.T("EditorMenuHeading5"), vm.Heading5Command),
        new("h6", Strings.T("EditorMenuHeading6"), vm.Heading6Command),
        new("cycleHeading", Strings.T("CmdHeadingCycle.Label"), vm.CycleHeadingCommand, "Ctrl+0"),
        new("promoteHeading", Strings.T("CmdPromoteHeading.Label"), vm.PromoteHeadingCommand, "Alt+Left"),
        new("demoteHeading", Strings.T("CmdDemoteHeading.Label"), vm.DemoteHeadingCommand, "Alt+Right"),
        new("renameHeading", Strings.T("CmdRenameHeading.Label"), vm.RenameHeadingCommand),
        new("format", Strings.T("CmdFormat.Label"), vm.FormatDocumentCommand, "Ctrl+Shift+I"),
        new("stripTrailing", Strings.T("CmdStripTrailingWhitespace.Label"), vm.StripTrailingWhitespaceCommand),
        new("comment", Strings.T("CmdComment.Label"), vm.ToggleCommentCommand, "Ctrl+/"),
        new("wiki", Strings.T("CmdWiki.Label"), vm.WikiCommand),
        new("footnote", Strings.T("CmdFootnote.Label"), vm.FootnoteCommand),
        new("callout", Strings.T("CmdCallout.Label"), vm.CalloutCommand),
        new("history", Strings.T("CmdHistory.Label"), vm.RestoreHistoryCommand),
        new("mermaid", Strings.T("CmdMermaid.Label"), vm.InsertMermaidCommand),
        new("star", Strings.T("CmdStar.Label"), vm.ToggleStarCommand),
        new("math", Strings.T("CmdMath.Label"), vm.InsertMathCommand),
        new("mathBlock", Strings.T("CmdMathBlock.Label"), vm.InsertMathBlockCommand),
        new("toc", Strings.T("CmdToc.Label"), vm.InsertTocCommand),
        new("copyHeading", Strings.T("CmdCopyHeading.Label"), vm.CopyHeadingLinkCommand),
        new("duplicateNote", Strings.T("CmdDuplicateNote.Label"), vm.DuplicateDocumentCommand),
        new("duplicate", Strings.T("CmdDuplicateLine.Label"), vm.DuplicateLineCommand, "Ctrl+D"),
        new("deleteLine", Strings.T("CmdDeleteLine.Label"), vm.DeleteLineCommand, "Ctrl+Shift+K"),
        new("selectLine", Strings.T("CmdSelectLine.Label"), vm.SelectLineCommand, "Ctrl+L"),
        new("moveUp", Strings.T("CmdMoveLineUp.Label"), vm.MoveLineUpCommand, "Ctrl+Shift+Up"),
        new("moveDown", Strings.T("CmdMoveLineDown.Label"), vm.MoveLineDownCommand, "Ctrl+Shift+Down"),
        new("moveHeadingUp", Strings.T("CmdMoveHeadingUp.Label"), vm.MoveHeadingUpCommand, "Alt+Up"),
        new("moveHeadingDown", Strings.T("CmdMoveHeadingDown.Label"), vm.MoveHeadingDownCommand, "Alt+Down"),
        new("selectHeading", Strings.T("CmdSelectHeading.Label"), vm.SelectHeadingCommand),
        new("foldHeading", Strings.T("CmdFoldHeading.Label"), vm.ToggleFoldHeadingCommand, "Ctrl+Shift+["),
        new("foldAll", Strings.T("CmdFoldAll.Label"), vm.FoldAllHeadingsCommand),
        new("unfoldAll", Strings.T("CmdUnfoldAll.Label"), vm.UnfoldAllHeadingsCommand),
        new("goToDefinition", Strings.T("CmdGoToDefinition.Label"), vm.GoToDefinitionCommand, "F12"),
        new("sort", Strings.T("CmdSortLines.Label"), vm.SortLinesCommand),
        new("reverseLines", Strings.T("CmdReverseLines.Label"), vm.ReverseLinesCommand),
        new("sortList", Strings.T("CmdSortList.Label"), vm.SortListCommand),
        new("duplicateListItem", Strings.T("CmdDuplicateListItem.Label"), vm.DuplicateListItemCommand),
        new("moveListUp", Strings.T("CmdMoveListItemUp.Label"), vm.MoveListItemUpCommand),
        new("moveListDown", Strings.T("CmdMoveListItemDown.Label"), vm.MoveListItemDownCommand),
        new("deleteListItem", Strings.T("CmdDeleteListItem.Label"), vm.DeleteListItemCommand),
        new("convertOrderedList", Strings.T("CmdConvertToOrderedList.Label"), vm.ConvertToOrderedListCommand),
        new("convertBulletList", Strings.T("CmdConvertToBulletList.Label"), vm.ConvertToBulletListCommand),
        new("cycleBullet", Strings.T("CmdCycleBulletMarker.Label"), vm.CycleBulletMarkerCommand),
        new("indentList", Strings.T("CmdIndentList.Label"), vm.IndentListCommand),
        new("outdentList", Strings.T("CmdOutdentList.Label"), vm.OutdentListCommand),
        new("quoteToCallout", Strings.T("CmdQuoteToCallout.Label"), vm.QuoteToCalloutCommand),
        new("calloutToQuote", Strings.T("CmdCalloutToQuote.Label"), vm.CalloutToQuoteCommand),
        new("cycleCallout", Strings.T("CmdCycleCalloutKind.Label"), vm.CycleCalloutKindCommand),
        new("linesToTaskList", Strings.T("CmdLinesToTaskList.Label"), vm.LinesToTaskListCommand),
        new("taskListToLines", Strings.T("CmdTaskListToLines.Label"), vm.TaskListToLinesCommand),
        new("join", Strings.T("CmdJoinLines.Label"), vm.JoinLinesCommand),
        new("reflow", Strings.T("CmdReflow.Label"), vm.ReflowParagraphCommand),
        new("upper", Strings.T("CmdUpper.Label"), vm.UppercaseCommand),
        new("lower", Strings.T("CmdLower.Label"), vm.LowercaseCommand),
        new("titleCase", Strings.T("CmdTitleCase.Label"), vm.TitleCaseCommand),
        new("sentenceCase", Strings.T("CmdSentenceCase.Label"), vm.SentenceCaseCommand),
        new("copyHtml", Strings.T("CmdCopyHtml.Label"), vm.CopyHtmlCommand, "Ctrl+Shift+C"),
        new("copyMd", Strings.T("CmdCopyMarkdown.Label"), vm.CopyMarkdownCommand),
        new("rename", Strings.T("CmdRename.Label"), vm.RenameCommand),
        new("share", Strings.T("CmdShare.Label"), vm.ShareCommand),
        new("immersive", Strings.T("CmdImmersive.Label"), vm.ToggleImmersiveCommand, "F11"),
        new("nextIssue", Strings.T("CmdNextIssue.Label"), vm.GoToNextIssueCommand, "F8"),
        new("prevIssue", Strings.T("CmdPrevIssue.Label"), vm.GoToPreviousIssueCommand, "Shift+F8"),
        new("wrap", Strings.T("CmdWordWrap.Label"), vm.ToggleWordWrapCommand),
        new("timestamp", Strings.T("CmdTimestamp.Label"), vm.InsertTimestampCommand),
        new("extractNote", Strings.T("CmdExtractNote.Label"), vm.ExtractToNoteCommand, "Ctrl+Shift+E"),
        new("copyWikilink", Strings.T("CmdCopyWikilink.Label"), vm.CopyWikilinkCommand),
        new("typographer", Strings.T("CmdTypographer.Label"), vm.TypographerCommand),
        new("slides", Strings.T("CmdSlides.Label"), vm.ToggleSlidesCommand, "F7"),
        new("nextSlide", Strings.T("CmdNextSlide.Label"), vm.NextSlideCommand, "Ctrl+PageDown"),
        new("prevSlide", Strings.T("CmdPrevSlide.Label"), vm.PreviousSlideCommand, "Ctrl+PageUp"),
        new("kanban", Strings.T("CmdKanban.Label"), vm.ToggleKanbanCommand, "F6"),
        new("splitVertical", Strings.T("CmdViewSplitVertical.Label"), vm.SplitVerticalCommand),
        new("focus", Strings.T("CmdFocus.Label"), vm.ToggleFocusCommand, "F10"),
        new("diff", Strings.T("CmdCompare.Label"), vm.ToggleDiffCommand),
        new("copyQuote", Strings.T("CmdCopyQuote.Label"), vm.CopyQuoteCommand),
        new("ensureId", Strings.T("CmdEnsureId.Label"), vm.EnsureNoteIdCommand),
        new("ensureTitle", Strings.T("CmdEnsureTitle.Label"), vm.EnsureNoteTitleCommand),
        new("ensureAlias", Strings.T("CmdEnsureAlias.Label"), vm.EnsureAliasCommand),
        new("ensureTags", Strings.T("CmdEnsureTags.Label"), vm.EnsureTagsCommand),
        new("ensureDescription", Strings.T("CmdEnsureDescription.Label"), vm.EnsureDescriptionCommand),
        new("ensureDate", Strings.T("CmdEnsureDate.Label"), vm.EnsureDateCommand),
        new("ensureStatus", Strings.T("CmdEnsureStatus.Label"), vm.EnsureStatusCommand),
        new("ensureAuthor", Strings.T("CmdEnsureAuthor.Label"), vm.EnsureAuthorCommand),
        new("ensureCssclass", Strings.T("CmdEnsureCssclass.Label"), vm.EnsureCssclassCommand),
        new("ensureLang", Strings.T("CmdEnsureLang.Label"), vm.EnsureLangCommand),
        new("ensureType", Strings.T("CmdEnsureType.Label"), vm.EnsureTypeCommand),
        new("stripEmptyYaml", Strings.T("CmdStripEmptyYamlKeys.Label"), vm.StripEmptyYamlKeysCommand),
        new("sortYamlKeys", Strings.T("CmdSortYamlKeys.Label"), vm.SortYamlKeysCommand),
        new("stripYamlKey", Strings.T("CmdStripYamlKey.Label"), vm.StripYamlKeyCommand),
        new("renameYamlKey", Strings.T("CmdRenameYamlKey.Label"), vm.RenameYamlKeyCommand),
        new("normalizeLists", Strings.T("CmdNormalizeListMarkers.Label"), vm.NormalizeListMarkersCommand),
        new("setextHeading", Strings.T("CmdToSetextHeading.Label"), vm.ToSetextHeadingCommand),
        new("fromSetextHeading", Strings.T("CmdFromSetextHeading.Label"), vm.FromSetextHeadingCommand),
        new("convertWiki", Strings.T("CmdConvertWikilinks.Label"), vm.ConvertWikilinksCommand),
        new("convertMd", Strings.T("CmdConvertMarkdownLinks.Label"), vm.ConvertMarkdownLinksCommand),
        new("unwrapWiki", Strings.T("CmdUnwrapWikilinks.Label"), vm.UnwrapWikilinksCommand),
        new("wrapDetails", Strings.T("CmdWrapDetails.Label"), vm.WrapDetailsCommand),
        new("unwrapDetails", Strings.T("CmdUnwrapDetails.Label"), vm.UnwrapDetailsCommand),
        new("duplicateHeading", Strings.T("CmdDuplicateHeading.Label"), vm.DuplicateHeadingCommand),
        new("blockId", Strings.T("CmdBlockId.Label"), vm.InsertBlockIdCommand),
        new("assignBlockIds", Strings.T("CmdAssignMissingBlockIds.Label"), vm.AssignMissingBlockIdsCommand),
        new("stripBlockIds", Strings.T("CmdStripBlockIds.Label"), vm.StripBlockIdsCommand),
        new("unwrapFence", Strings.T("CmdUnwrapFence.Label"), vm.UnwrapFenceCommand),
        new("setFenceLanguage", Strings.T("CmdSetFenceLanguage.Label"), vm.SetFenceLanguageCommand),
        new("stripHtmlComments", Strings.T("CmdStripHtmlComments.Label"), vm.StripHtmlCommentsCommand),
        new("stampUpdated", Strings.T("CmdStampUpdated.Label"), vm.StampUpdatedCommand),
        new("numberHeadings", Strings.T("CmdNumberHeadings.Label"), vm.NumberHeadingsCommand),
        new("bibliography", Strings.T("CmdBibliography.Label"), vm.InsertBibliographyCommand),
    ];

    public static IReadOnlyList<PaletteCommand> Filter(EditorViewModel vm, string query)
        => PaletteFilter.Apply(Commands(vm), command => string.Join(' ', command.Id, command.Label, command.Shortcut), query);
}
