using MarkdownMkII.Core.Markdown;
using MarkdownMkII.Core.Services;
using MarkdownMkII.Core.Text;

namespace MarkdownMkII.Core.Tests;

public partial class CatalogCompatibilityTests
{
    private static readonly CompatibilityCase[] Cases =
    [
        new("Pubchem_BpmnPuml_AuthorDate_Parents_And_Yaml", MarkdownEditing.LooksLikePubchem,
            ["2244", "https://pubchem.ncbi.nlm.nih.gov/compound/2244", "pubchem:2244"], ["not-pubchem", "Q42"],
            ["authordate", "logparents"],
            new(FrontMatter.EnsureAtrium, folders => WikiIndex.NotesWithoutAtrium(folders), "Nord", "atrium: Nord"),
            new(FrontMatter.EnsureTerrace, folders => WikiIndex.NotesWithoutTerrace(folders), "3", "terrace: 3"),
            "@startbpmn\nstart\n:Task;\nend\n@endbpmn\n", ["start", ":Task;"], "w0", "w1", "bpmn", "@startbpmn",
            "---\npubchem: 2244\natrium: Nord\nterrace: 3\n---\n# B\n", "---\npubchem: nope\n---\n# N\n", "pubchem IS PUBCHEM"),
        new("Smiles_FilesPuml_Skip_NoAbbrev_And_Yaml", MarkdownEditing.LooksLikeSmiles,
            ["CCO", "smiles:CCO"], ["not-smiles", "Q42"],
            ["logskip", "noabbrev"],
            new(FrontMatter.EnsurePier, folders => WikiIndex.NotesWithoutPier(folders), "Sud", "pier: Sud"),
            new(FrontMatter.EnsureHarbor, folders => WikiIndex.NotesWithoutHarbor(folders), "6", "harbor: 6"),
            "@startfiles\nfile App\nfile Core\n@endfiles\n", ["App", "Core"], "z0", "z1", "filespuml", "@startfiles",
            "---\nsmiles: CCO\npier: Sud\nharbor: 6\n---\n# B\n", "---\nsmiles: xyz\n---\n# N\n", "smiles IS SMILES"),
        new("Unii_JcckitPuml_Source_Mailmap_And_Yaml", MarkdownEditing.LooksLikeUnii,
            ["3G6A5W338E", "unii:3G6A5W338E", "https://precision.fda.gov/uniisearch/srs/unii/3G6A5W338E"], ["not-unii", "Q42"],
            ["logsource", "mailmap"],
            new(FrontMatter.EnsureQuay, folders => WikiIndex.NotesWithoutQuay(folders), "Nord", "quay: Nord"),
            new(FrontMatter.EnsureMarina, folders => WikiIndex.NotesWithoutMarina(folders), "7", "marina: 7"),
            "@startjcckit\nChart\nPlot\n@endjcckit\n", ["Chart", "Plot"], "q0", "q1", "jcckit", "@startjcckit",
            "---\nunii: 3G6A5W338E\nquay: Nord\nmarina: 7\n---\n# B\n", "---\nunii: not-unii\n---\n# N\n", "unii IS UNII"),
        new("Chemspider_WirevizPuml_Pretty_NoWalk_And_Yaml", MarkdownEditing.LooksLikeChemspider,
            ["236", "chemspider:236", "csid:236", "https://www.chemspider.com/Chemical-Structure.236.html"], ["not-csid", "Q42"],
            ["logpretty", "nowalk"],
            new(FrontMatter.EnsureWharf, folders => WikiIndex.NotesWithoutWharf(folders), "Est", "wharf: Est"),
            new(FrontMatter.EnsureBreakwater, folders => WikiIndex.NotesWithoutBreakwater(folders), "8", "breakwater: 8"),
            "@startwireviz\nPower\nGround\n@endwireviz\n", ["Power", "Ground"], "y0", "y1", "wireviz", "@startwireviz",
            "---\nchemspider: 236\nwharf: Est\nbreakwater: 8\n---\n# B\n", "---\nchemspider: not-csid\n---\n# N\n", "chemspider IS CHEMSPIDER"),
        new("Chebi_ProjectPuml_Abbrev_NoColor_And_Yaml", MarkdownEditing.LooksLikeChebi,
            ["15377", "chebi:15377", "CHEBI:15377", "https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15377"], ["not-chebi", "Q42"],
            ["logabbrev", "nocolor"],
            new(FrontMatter.EnsureJetty, folders => WikiIndex.NotesWithoutJetty(folders), "Ovest", "jetty: Ovest"),
            new(FrontMatter.EnsureLighthouse, folders => WikiIndex.NotesWithoutLighthouse(folders), "9", "lighthouse: 9"),
            "@startproject\nDesign\nCode\n@endproject\n", ["Design", "Code"], "o0", "o1", "projectpuml", "@startproject",
            "---\nchebi: 15377\njetty: Ovest\nlighthouse: 9\n---\n# B\n", "---\nchebi: not-chebi\n---\n# N\n", "chebi IS CHEBI"),
        new("Ec_DotPuml_DateShort_Encoding_And_Yaml", MarkdownEditing.LooksLikeEc,
            ["1.1.1.1", "ec:1.14.13.25", "https://enzyme.expasy.org/EC/1.1.1.1"], ["not-ec", "1.1.1", "Q42"],
            ["dateshort", "logencoding"],
            new(FrontMatter.EnsureCove, folders => WikiIndex.NotesWithoutCove(folders), "Nord", "cove: Nord"),
            new(FrontMatter.EnsureInlet, folders => WikiIndex.NotesWithoutInlet(folders), "10", "inlet: 10"),
            "@startdot\nApp\nCore\n@enddot\n", ["App", "Core"], "n0", "n1", "dotpuml", "@startdot",
            "---\nec: 1.1.1.1\ncove: Nord\ninlet: 10\n---\n# B\n", "---\nec: not-ec\n---\n# N\n", "ec IS EC"),
        new("Mesh_NeatoPuml_Follow_Boundary_And_Yaml", MarkdownEditing.LooksLikeMesh,
            ["D000001", "mesh:D000001", "https://id.nlm.nih.gov/mesh/D000001"], ["not-mesh", "D12", "Q42"],
            ["logfollow", "logboundary"],
            new(FrontMatter.EnsureReef, folders => WikiIndex.NotesWithoutReef(folders), "Est", "reef: Est"),
            new(FrontMatter.EnsureShoal, folders => WikiIndex.NotesWithoutShoal(folders), "11", "shoal: 11"),
            "@startneato\nApp\nCore\n@endneato\n", ["App", "Core"], "m0", "m1", "neato", "@startneato",
            "---\nmesh: D000001\nreef: Est\nshoal: 11\n---\n# B\n", "---\nmesh: not-mesh\n---\n# N\n", "mesh IS MESH"),
        new("Hmdb_CircoPuml_LeftRight_CherryMark_And_Yaml", MarkdownEditing.LooksLikeHmdb,
            ["HMDB00001", "hmdb:HMDB0000001", "https://hmdb.ca/metabolites/HMDB00001"], ["not-hmdb", "Q42", "HMDB12"],
            ["leftright", "cherrymark"],
            new(FrontMatter.EnsureDelta, folders => WikiIndex.NotesWithoutDelta(folders), "delta-1", "delta: delta-1"),
            new(FrontMatter.EnsureEstuary, folders => WikiIndex.NotesWithoutEstuary(folders), "estuary-1", "estuary: estuary-1"),
            "@startcirco\nApp\nCore\n@endcirco\n", ["App", "Core"], "r0", "r1", "circo", "@startcirco",
            "---\nhmdb: HMDB00001\ndelta: delta-1\nestuary: estuary-1\n---\n# B\n", "---\nhmdb: not-hmdb\n---\n# N\n", "hmdb IS HMDB"),
        new("Kegg_FdpPuml_Simplify_SimplifyMerges_And_Yaml", MarkdownEditing.LooksLikeKegg,
            ["C00031", "kegg:C00031", "https://www.kegg.jp/entry/C00031"], ["not-kegg", "Q42", "C12", "HMDB00001"],
            ["simpdec", "simpmerges"],
            new(FrontMatter.EnsureLagoon, folders => WikiIndex.NotesWithoutLagoon(folders), "lagoon-1", "lagoon: lagoon-1"),
            new(FrontMatter.EnsureSpit, folders => WikiIndex.NotesWithoutSpit(folders), "spit-1", "spit: spit-1"),
            "@startfdp\nApp\nCore\n@endfdp\n", ["App", "Core"], "s0", "s1", "fdp", "@startfdp",
            "---\nkegg: C00031\nlagoon: lagoon-1\nspit: spit-1\n---\n# B\n", "---\nkegg: not-kegg\n---\n# N\n", "kegg IS KEGG"),
        new("Chembl_TwopiPuml_FullHistory_Ancestry_And_Yaml", MarkdownEditing.LooksLikeChembl,
            ["CHEMBL25", "chembl:CHEMBL25", "https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL25"], ["not-chembl", "C00031", "CHEMBL", "CHEMBL0"],
            ["fullhist", "ancestry"],
            new(FrontMatter.EnsureAtoll, folders => WikiIndex.NotesWithoutAtoll(folders), "atoll-1", "atoll: atoll-1"),
            new(FrontMatter.EnsureFjord, folders => WikiIndex.NotesWithoutFjord(folders), "fjord-1", "fjord: fjord-1"),
            "@starttwopi\nApp\nCore\n@endtwopi\n", ["App", "Core"], "t0", "t1", "twopi", "@starttwopi",
            "---\nchembl: CHEMBL25\natoll: atoll-1\nfjord: fjord-1\n---\n# B\n", "---\nchembl: not-chembl\n---\n# N\n", "chembl IS CHEMBL"),
        new("InchiKey_OsagePuml_RemoveEmpty_ShowPulls_And_Yaml", MarkdownEditing.LooksLikeInchiKey,
            ["BSYNRYMUTXBXSQ-UHFFFAOYSA-N", "inchikey:BSYNRYMUTXBXSQ-UHFFFAOYSA-N", "https://pubchem.ncbi.nlm.nih.gov/#query=BSYNRYMUTXBXSQ-UHFFFAOYSA-N"], ["not-key", "CHEMBL25", "InChI=1S/C2H6O/c1-2-3/h3H,2H2,1H3", "BSYNRYMUTXBXSQ"],
            ["remempty", "showpulls"],
            new(FrontMatter.EnsureCape, folders => WikiIndex.NotesWithoutCape(folders), "cape-1", "cape: cape-1"),
            new(FrontMatter.EnsurePeninsula, folders => WikiIndex.NotesWithoutPeninsula(folders), "peninsula-1", "peninsula: peninsula-1"),
            "@startosage\nApp\nCore\n@endosage\n", ["App", "Core"], "p0", "p1", "osage", "@startosage",
            "---\ninchikey: BSYNRYMUTXBXSQ-UHFFFAOYSA-N\ncape: cape-1\npeninsula: peninsula-1\n---\n# B\n", "---\ninchikey: not-key\n---\n# N\n", "inchikey IS INCHIKEY"),
        new("Drugbank_PatchworkPuml_LeftOnly_RightOnly_And_Yaml", MarkdownEditing.LooksLikeDrugbank,
            ["DB00001", "drugbank:DB00006", "https://go.drugbank.com/drugs/DB00001"], ["not-db", "CHEMBL25", "DB12", "DB000001"],
            ["leftonly", "rightonly"],
            new(FrontMatter.EnsureGulf, folders => WikiIndex.NotesWithoutGulf(folders), "gulf-1", "gulf: gulf-1"),
            new(FrontMatter.EnsureStrait, folders => WikiIndex.NotesWithoutStrait(folders), "strait-1", "strait: strait-1"),
            "@startpatchwork\nApp\nCore\n@endpatchwork\n", ["App", "Core"], "g0", "g1", "patchwork", "@startpatchwork",
            "---\ndrugbank: DB00001\ngulf: gulf-1\nstrait: strait-1\n---\n# B\n", "---\ndrugbank: not-db\n---\n# N\n", "drugbank IS DRUGBANK"),
        new("Pdb_SfdpPuml_MaxParents_MinParents_And_Yaml", MarkdownEditing.LooksLikePdb,
            ["1ABC", "pdb:4HHB", "https://www.rcsb.org/structure/1ABC"], ["not-pdb", "0ABC", "ABCD", "1AB"],
            ["maxparents", "minparents"],
            new(FrontMatter.EnsureIsthmus, folders => WikiIndex.NotesWithoutIsthmus(folders), "isthmus-1", "isthmus: isthmus-1"),
            new(FrontMatter.EnsureArchipelago, folders => WikiIndex.NotesWithoutArchipelago(folders), "archipelago-1", "archipelago: archipelago-1"),
            "@startsfdp\nApp\nCore\n@endsfdp\n", ["App", "Core"], "f0", "f1", "sfdp", "@startsfdp",
            "---\npdb: 1ABC\nisthmus: isthmus-1\narchipelago: archipelago-1\n---\n# B\n", "---\npdb: not-pdb\n---\n# N\n", "pdb IS PDB"),
        new("Uniprot_NopPuml_InvertGrep_FixedStrings_And_Yaml", MarkdownEditing.LooksLikeUniprot,
            ["P04637", "uniprot:Q9Y6K9", "https://www.uniprot.org/uniprotkb/P04637"], ["not-up", "1ABC", "P0463"],
            ["invgrep", "fixedstr"],
            new(FrontMatter.EnsureBayou, folders => WikiIndex.NotesWithoutBayou(folders), "bayou-1", "bayou: bayou-1"),
            new(FrontMatter.EnsureTombolo, folders => WikiIndex.NotesWithoutTombolo(folders), "tombolo-1", "tombolo: tombolo-1"),
            "@startnop\nApp\nCore\n@endnop\n", ["App", "Core"], "e0", "e1", "nop", "@startnop",
            "---\nuniprot: P04637\nbayou: bayou-1\ntombolo: tombolo-1\n---\n# B\n", "---\nuniprot: not-up\n---\n# N\n", "uniprot IS UNIPROT"),
        new("Ensembl_RackPuml_RegexpIgnoreCase_AllMatch_And_Yaml", MarkdownEditing.LooksLikeEnsembl,
            ["ENSG00000139618", "ensembl:ENST00000380152", "https://www.ensembl.org/id/ENSG00000139618"], ["not-ens", "ENSG123", "G00000139618"],
            ["igncase", "allmatch"],
            new(FrontMatter.EnsureBight, folders => WikiIndex.NotesWithoutBight(folders), "bight-1", "bight: bight-1"),
            new(FrontMatter.EnsureFirth, folders => WikiIndex.NotesWithoutFirth(folders), "firth-1", "firth: firth-1"),
            "@startrackdiag\nApp\nCore\n@endrackdiag\n", ["App", "Core"], "a0", "a1", "rack", "@startrackdiag",
            "---\nensembl: ENSG00000139618\nbight: bight-1\nfirth: firth-1\n---\n# B\n", "---\nensembl: not-ens\n---\n# N\n", "ensembl IS ENSEMBL"),
        new("Rhea_PacketPuml_ExtendedRegexp_PerlRegexp_And_Yaml", MarkdownEditing.LooksLikeRhea,
            ["10716", "rhea:10716", "https://www.rhea-db.org/rhea/10716"], ["not-rhea", "0123", "rhea:0"],
            ["extre", "perlre"],
            new(FrontMatter.EnsureRia, folders => WikiIndex.NotesWithoutRia(folders), "ria-1", "ria: ria-1"),
            new(FrontMatter.EnsureLoch, folders => WikiIndex.NotesWithoutLoch(folders), "loch-1", "loch: loch-1"),
            "@startpacketdiag\nApp\nCore\n@endpacketdiag\n", ["App", "Core"], "b0", "b1", "packetpuml", "@startpacketdiag",
            "---\nrhea: 10716\nria: ria-1\nloch: loch-1\n---\n# B\n", "---\nrhea: not-rhea\n---\n# N\n", "rhea IS RHEA"),
        new("Lincs_C4Puml_BasicRegexp_GrepReflog_And_Yaml", MarkdownEditing.LooksLikeLincs,
            ["LSM-1232", "lincs:LSM-4321", "https://lincs.hms.harvard.edu/db/sm/LSM-1232"], ["not-lincs", "LSM-abc", "LSM1232", "LSM-0"],
            ["basicre", "grepreflog"],
            new(FrontMatter.EnsureBasin, folders => WikiIndex.NotesWithoutBasin(folders), "basin-1", "basin: basin-1"),
            new(FrontMatter.EnsureTrench, folders => WikiIndex.NotesWithoutTrench(folders), "trench-1", "trench: trench-1"),
            "@startc4\nApp\nCore\n@endc4\n", ["App", "Core"], "d0", "d1", "c4puml", "@startc4",
            "---\nlincs: LSM-1232\nbasin: basin-1\ntrench: trench-1\n---\n# B\n", "---\nlincs: not-lincs\n---\n# N\n", "lincs IS LINCS"),
        new("Hgnc_ElkPuml_WalkReflogs_LogSize_And_Yaml", MarkdownEditing.LooksLikeHgnc,
            ["1100", "hgnc:1100", "https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:1100"], ["not-hgnc", "0", "HGNC:abc"],
            ["walkreflog", "logsize"],
            new(FrontMatter.EnsureShelf, folders => WikiIndex.NotesWithoutShelf(folders), "shelf-1", "shelf: shelf-1"),
            new(FrontMatter.EnsureRise, folders => WikiIndex.NotesWithoutRise(folders), "rise-1", "rise: rise-1"),
            "@startelk\nApp\nCore\n@endelk\n", ["App", "Core"], "i0", "i1", "elk", "@startelk",
            "---\nhgnc: 1100\nshelf: shelf-1\nrise: rise-1\n---\n# B\n", "---\nhgnc: not-hgnc\n---\n# N\n", "hgnc IS HGNC"),
        new("Go_SmetanaPuml_FullDiff_Fuller_And_Yaml", MarkdownEditing.LooksLikeGo,
            ["0008150", "GO:0008150", "go:0008150", "https://amigo.geneontology.org/amigo/term/GO:0008150"], ["not-go", "GO:8150", "GO:abc"],
            ["fulldiff", "fuller"],
            new(FrontMatter.EnsureAbyss, folders => WikiIndex.NotesWithoutAbyss(folders), "abyss-1", "abyss: abyss-1"),
            new(FrontMatter.EnsureRidge, folders => WikiIndex.NotesWithoutRidge(folders), "ridge-1", "ridge: ridge-1"),
            "@startsmetana\nApp\nCore\n@endsmetana\n", ["App", "Core"], "j0", "j1", "smetana", "@startsmetana",
            "---\ngo: GO:0008150\nabyss: abyss-1\nridge: ridge-1\n---\n# B\n", "---\ngo: not-go\n---\n# N\n", "go IS GO"),
        new("Interpro_VizjsPuml_PrettyFull_PrettyRaw_And_Yaml", MarkdownEditing.LooksLikeInterpro,
            ["IPR000001", "interpro:IPR000001", "https://www.ebi.ac.uk/interpro/entry/InterPro/IPR000001"], ["not-interpro", "IPR1", "IPRABC123"],
            ["prettyfull", "prettyraw"],
            new(FrontMatter.EnsureCanyon, folders => WikiIndex.NotesWithoutCanyon(folders), "canyon-1", "canyon: canyon-1"),
            new(FrontMatter.EnsureSlope, folders => WikiIndex.NotesWithoutSlope(folders), "slope-1", "slope: slope-1"),
            "@startvizjs\nApp\nCore\n@endvizjs\n", ["App", "Core"], "k0", "k1", "vizjs", "@startvizjs",
            "---\ninterpro: IPR000001\ncanyon: canyon-1\nslope: slope-1\n---\n# B\n", "---\ninterpro: not-interpro\n---\n# N\n", "interpro IS INTERPRO"),
        new("Pfam_SvekPuml_PrettyEmail_PrettyReference_And_Yaml", MarkdownEditing.LooksLikePfam,
            ["PF00001", "pfam:PF00001", "https://www.ebi.ac.uk/interpro/entry/pfam/PF00001"], ["not-pfam", "PF1", "PFABC12"],
            ["prettyemail", "prettyref"],
            new(FrontMatter.EnsureSeamount, folders => WikiIndex.NotesWithoutSeamount(folders), "seamount-1", "seamount: seamount-1"),
            new(FrontMatter.EnsureGuyot, folders => WikiIndex.NotesWithoutGuyot(folders), "guyot-1", "guyot: guyot-1"),
            "@startsvek\nApp\nCore\n@endsvek\n", ["App", "Core"], "l0", "l1", "svek", "@startsvek",
            "---\npfam: PF00001\nseamount: seamount-1\nguyot: guyot-1\n---\n# B\n", "---\npfam: not-pfam\n---\n# N\n", "pfam IS PFAM"),
        new("Reactome_TeozPuml_DateIso_DateRelative_And_Yaml", MarkdownEditing.LooksLikeReactome,
            ["R-HSA-73857", "reactome:R-HSA-73857", "https://reactome.org/content/detail/R-HSA-73857"], ["not-reactome", "R-HSA-0", "R-HSA-abc"],
            ["dateiso", "daterel"],
            new(FrontMatter.EnsureTrough, folders => WikiIndex.NotesWithoutTrough(folders), "trough-1", "trough: trough-1"),
            new(FrontMatter.EnsureSill, folders => WikiIndex.NotesWithoutSill(folders), "sill-1", "sill: sill-1"),
            "@startteoz\nApp\nCore\n@endteoz\n", ["App", "Core"], "m0", "m1", "teoz", "@startteoz",
            "---\nreactome: R-HSA-73857\ntrough: trough-1\nsill: sill-1\n---\n# B\n", "---\nreactome: not-reactome\n---\n# N\n", "reactome IS REACTOME"),
        new("Refseq_PicPuml_PrettyMedium_PrettyMbox_And_Yaml", MarkdownEditing.LooksLikeRefseq,
            ["NM_000546", "NP_000001.1", "refseq:NM_000546", "https://www.ncbi.nlm.nih.gov/nuccore/NM_000546"], ["not-refseq", "NM_1", "NM_abc"],
            ["prettymedium", "prettymbox"],
            new(FrontMatter.EnsureKnoll, folders => WikiIndex.NotesWithoutKnoll(folders), "knoll-1", "knoll: knoll-1"),
            new(FrontMatter.EnsureSpur, folders => WikiIndex.NotesWithoutSpur(folders), "spur-1", "spur: spur-1"),
            "@startpic\nApp\nCore\n@endpic\n", ["App", "Core"], "n0", "n1", "picpuml", "@startpic",
            "---\nrefseq: NM_000546\nknoll: knoll-1\nspur: spur-1\n---\n# B\n", "---\nrefseq: not-refseq\n---\n# N\n", "refseq IS REFSEQ"),
        new("Mgi_CreolePuml_DateIsoStrict_DateRfc_And_Yaml", MarkdownEditing.LooksLikeMgi,
            ["MGI:96677", "mgi:MGI:96677", "https://www.informatics.jax.org/marker/MGI:96677"], ["not-mgi", "MGI:0", "MGI:abc"],
            ["dateisostrict", "daterfc"],
            new(FrontMatter.EnsureMesa, folders => WikiIndex.NotesWithoutMesa(folders), "mesa-1", "mesa: mesa-1"),
            new(FrontMatter.EnsureButte, folders => WikiIndex.NotesWithoutButte(folders), "butte-1", "butte: butte-1"),
            "@startcreole\nApp\nCore\n@endcreole\n", ["App", "Core"], "o0", "o1", "creole", "@startcreole",
            "---\nmgi: MGI:96677\nmesa: mesa-1\nbutte: butte-1\n---\n# B\n", "---\nmgi: not-mgi\n---\n# N\n", "mgi IS MGI"),
        new("Flybase_EpsPuml_DateUnix_DateLocal_And_Yaml", MarkdownEditing.LooksLikeFlybase,
            ["FBgn0000003", "flybase:FBgn0000003", "https://flybase.org/reports/FBgn0000003"], ["not-flybase", "FBgn1", "FBgnABC"],
            ["dateunix", "datelocal"],
            new(FrontMatter.EnsureCliff, folders => WikiIndex.NotesWithoutCliff(folders), "cliff-1", "cliff: cliff-1"),
            new(FrontMatter.EnsureBluff, folders => WikiIndex.NotesWithoutBluff(folders), "bluff-1", "bluff: bluff-1"),
            "@starteps\nApp\nCore\n@endeps\n", ["App", "Core"], "p0", "p1", "eps", "@starteps",
            "---\nflybase: FBgn0000003\ncliff: cliff-1\nbluff: bluff-1\n---\n# B\n", "---\nflybase: not-flybase\n---\n# N\n", "flybase IS FLYBASE"),
        new("Wormbase_UmletPuml_DateRaw_DateHuman_And_Yaml", MarkdownEditing.LooksLikeWormbase,
            ["WBGene00000001", "wormbase:WBGene00000001", "https://www.wormbase.org/species/c_elegans/gene/WBGene00000001", "https://wormbase.org/species/c_elegans/gene/WBGene00000001"], ["not-wormbase", "WBGene1", "WBGeneABC"],
            ["dateraw", "datehuman"],
            new(FrontMatter.EnsureCrag, folders => WikiIndex.NotesWithoutCrag(folders), "crag-1", "crag: crag-1"),
            new(FrontMatter.EnsureTor, folders => WikiIndex.NotesWithoutTor(folders), "tor-1", "tor: tor-1"),
            "@startumlet\nApp\nCore\n@endumlet\n", ["App", "Core"], "q0", "q1", "umlet", "@startumlet",
            "---\nwormbase: WBGene00000001\ncrag: crag-1\ntor: tor-1\n---\n# B\n", "---\nwormbase: not-wormbase\n---\n# N\n", "wormbase IS WORMBASE"),
        new("Sgd_JlatexmathPuml_PrettyShort_PrettyOneline_And_Yaml", MarkdownEditing.LooksLikeSgd,
            ["S000000001", "sgd:S000000001", "https://www.yeastgenome.org/locus/S000000001", "https://yeastgenome.org/locus/S000000001"], ["not-sgd", "S1", "SABCDEFGHI"],
            ["prettyshort", "prettyoneline"],
            new(FrontMatter.EnsurePeak, folders => WikiIndex.NotesWithoutPeak(folders), "peak-1", "peak: peak-1"),
            new(FrontMatter.EnsureSummit, folders => WikiIndex.NotesWithoutSummit(folders), "summit-1", "summit: summit-1"),
            "@startjlatexmath\nApp\nCore\n@endjlatexmath\n", ["App", "Core"], "r0", "r1", "jlatexmath", "@startjlatexmath",
            "---\nsgd: S000000001\npeak: peak-1\nsummit: summit-1\n---\n# B\n", "---\nsgd: not-sgd\n---\n# N\n", "sgd IS SGD"),
        new("Zfin_CutePuml_DateIsoLocal_DateDefault_And_Yaml", MarkdownEditing.LooksLikeZfin,
            ["ZDB-GENE-980526-166", "zfin:ZDB-GENE-980526-166", "https://zfin.org/ZDB-GENE-980526-166", "https://www.zfin.org/ZDB-GENE-980526-166"], ["not-zfin", "ZDB-GENE-1", "ZDB-GENE-ABCDEF"],
            ["dateisolocal", "datedefault"],
            new(FrontMatter.EnsureCirque, folders => WikiIndex.NotesWithoutCirque(folders), "cirque-1", "cirque: cirque-1"),
            new(FrontMatter.EnsureArete, folders => WikiIndex.NotesWithoutArete(folders), "arete-1", "arete: arete-1"),
            "@startcute\nApp\nCore\n@endcute\n", ["App", "Core"], "s0", "s1", "cute", "@startcute",
            "---\nzfin: ZDB-GENE-980526-166\ncirque: cirque-1\narete: arete-1\n---\n# B\n", "---\nzfin: not-zfin\n---\n# N\n", "zfin IS ZFIN"),
        new("Rgd_FlowPuml_DateIso8601_DateIsoStrictLocal_And_Yaml", MarkdownEditing.LooksLikeRgd,
            ["620305", "rgd:620305", "RGD:620305", "https://rgd.mcw.edu/rgdweb/report/gene/main.html?id=620305", "https://www.rgd.mcw.edu/rgdweb/report/gene/main.html?id=620305"], ["not-rgd", "0", "RGDabc"],
            ["dateiso8601", "dateisostrictlocal"],
            new(FrontMatter.EnsureScree, folders => WikiIndex.NotesWithoutScree(folders), "scree-1", "scree: scree-1"),
            new(FrontMatter.EnsureGully, folders => WikiIndex.NotesWithoutGully(folders), "gully-1", "gully: gully-1"),
            "@startflow\nApp\nCore\n@endflow\n", ["App", "Core"], "t0", "t1", "flowpuml", "@startflow",
            "---\nrgd: 620305\nscree: scree-1\ngully: gully-1\n---\n# B\n", "---\nrgd: not-rgd\n---\n# N\n", "rgd IS RGD"),
        new("Tair_DefPuml_DateRfc3339_DateFormat_And_Yaml", MarkdownEditing.LooksLikeTair,
            ["AT1G01010", "tair:AT1G01010", "https://www.arabidopsis.org/servlets/TairObject?type=locus&name=AT1G01010", "https://arabidopsis.org/servlets/TairObject?type=locus&name=AT1G01010"], ["not-tair", "AT1", "ATGABCDE"],
            ["daterfc3339", "dateformat"],
            new(FrontMatter.EnsureMoraine, folders => WikiIndex.NotesWithoutMoraine(folders), "moraine-1", "moraine: moraine-1"),
            new(FrontMatter.EnsureGlacier, folders => WikiIndex.NotesWithoutGlacier(folders), "glacier-1", "glacier: glacier-1"),
            "@startdef\nApp\nCore\n@enddef\n", ["App", "Core"], "u0", "u1", "defpuml", "@startdef",
            "---\ntair: AT1G01010\nmoraine: moraine-1\nglacier: glacier-1\n---\n# B\n", "---\ntair: not-tair\n---\n# N\n", "tair IS TAIR"),
        new("Xenbase_MapPuml_DateFormatLocal_PrettyFormat_And_Yaml", MarkdownEditing.LooksLikeXenbase,
            ["XB-GENE-478054", "xenbase:XB-GENE-478054", "https://www.xenbase.org/entry/XB-GENE-478054", "https://xenbase.org/entry/XB-GENE-478054"], ["not-xenbase", "XB-GENE-0", "XB-GENE-ABC"],
            ["dateformatlocal", "prettyformat"],
            new(FrontMatter.EnsureCouloir, folders => WikiIndex.NotesWithoutCouloir(folders), "couloir-1", "couloir: couloir-1"),
            new(FrontMatter.EnsureSerac, folders => WikiIndex.NotesWithoutSerac(folders), "serac-1", "serac: serac-1"),
            "@startmap\nApp\nCore\n@endmap\n", ["App", "Core"], "v0", "v1", "mappuml", "@startmap",
            "---\nxenbase: XB-GENE-478054\ncouloir: couloir-1\nserac: serac-1\n---\n# B\n", "---\nxenbase: not-xenbase\n---\n# N\n", "xenbase IS XENBASE"),
        new("PomBase_ListPuml_DateRfcLocal_DateShortLocal_And_Yaml", MarkdownEditing.LooksLikePomBase,
            ["SPAC2F7.11c", "pombase:SPAC2F7.11c", "https://www.pombase.org/gene/SPAC2F7.11c", "https://pombase.org/gene/SPAC2F7.11c"], ["not-pombase", "SPAC", "SPZC2F7.11c"],
            ["daterfclocal", "dateshortlocal"],
            new(FrontMatter.EnsureCrevasse, folders => WikiIndex.NotesWithoutCrevasse(folders), "crevasse-1", "crevasse: crevasse-1"),
            new(FrontMatter.EnsureHorn, folders => WikiIndex.NotesWithoutHorn(folders), "horn-1", "horn: horn-1"),
            "@startlist\nApp\nCore\n@endlist\n", ["App", "Core"], "w0", "w1", "listpuml", "@startlist",
            "---\npombase: SPAC2F7.11c\ncrevasse: crevasse-1\nhorn: horn-1\n---\n# B\n", "---\npombase: not-pombase\n---\n# N\n", "pombase IS POMBASE"),
        new("DictyBase_NetworkPuml_DateDefaultLocal_PrettyTformat_And_Yaml", MarkdownEditing.LooksLikeDictyBase,
            ["DDB_G0267372", "dictybase:DDB_G0267372", "https://www.dictybase.org/gene/DDB_G0267372", "https://dictybase.org/gene/DDB_G0267372"], ["not-dictybase", "DDB_G0", "DDB_GABCDEFG"],
            ["datedefaultlocal", "prettytformat"],
            new(FrontMatter.EnsureIcefall, folders => WikiIndex.NotesWithoutIcefall(folders), "icefall-1", "icefall: icefall-1"),
            new(FrontMatter.EnsureNunatak, folders => WikiIndex.NotesWithoutNunatak(folders), "nunatak-1", "nunatak: nunatak-1"),
            "@startnetwork\nApp\nCore\n@endnetwork\n", ["App", "Core"], "x0", "x1", "networkpuml", "@startnetwork",
            "---\ndictybase: DDB_G0267372\nicefall: icefall-1\nnunatak: nunatak-1\n---\n# B\n", "---\ndictybase: not-dictybase\n---\n# N\n", "dictybase IS DICTYBASE"),
        new("EcoCyc_XmiPuml_DateRelativeLocal_PrettyAe_And_Yaml", MarkdownEditing.LooksLikeEcoCyc,
            ["EG10572", "ecocyc:EG10572", "https://www.ecocyc.org/gene?orgid=ECOLI&id=EG10572", "https://ecocyc.org/gene?orgid=ECOLI&id=EG10572"], ["not-ecocyc", "EG1", "EGABCDE"],
            ["daterelativelocal", "prettyae"],
            new(FrontMatter.EnsureFirn, folders => WikiIndex.NotesWithoutFirn(folders), "firn-1", "firn: firn-1"),
            new(FrontMatter.EnsureNeve, folders => WikiIndex.NotesWithoutNeve(folders), "neve-1", "neve: neve-1"),
            "@startxmi\nApp\nCore\n@endxmi\n", ["App", "Core"], "y0", "y1", "xmipuml", "@startxmi",
            "---\necocyc: EG10572\nfirn: firn-1\nneve: neve-1\n---\n# B\n", "---\necocyc: not-ecocyc\n---\n# N\n", "ecocyc IS ECOCYC"),
        new("Cgd_ScxmlPuml_DateIso8601Local_PrettyCn_And_Yaml", MarkdownEditing.LooksLikeCgd,
            ["CAL0000196", "cgd:CAL0000196", "https://www.candidagenome.org/cgi-bin/locus.pl?locus=CAL0000196", "https://candidagenome.org/cgi-bin/locus.pl?locus=CAL0000196"], ["not-cgd", "CAL1", "CALABCDEF"],
            ["dateiso8601local", "prettycn"],
            new(FrontMatter.EnsureBergschrund, folders => WikiIndex.NotesWithoutBergschrund(folders), "bergschrund-1", "bergschrund: bergschrund-1"),
            new(FrontMatter.EnsureIcefield, folders => WikiIndex.NotesWithoutIcefield(folders), "icefield-1", "icefield: icefield-1"),
            "@startscxml\nApp\nCore\n@endscxml\n", ["App", "Core"], "z0", "z1", "scxmlpuml", "@startscxml",
            "---\ncgd: CAL0000196\nbergschrund: bergschrund-1\nicefield: icefield-1\n---\n# B\n", "---\ncgd: not-cgd\n---\n# N\n", "cgd IS CGD"),
        new("VectorBase_JunglePuml_PrettyCe_DateFormatYm_And_Yaml", MarkdownEditing.LooksLikeVectorBase,
            ["AGAP004707", "vectorbase:AGAP004707", "https://www.vectorbase.org/gene/AGAP004707", "https://vectorbase.org/gene/AGAP004707"], ["not-vectorbase", "AGAP1", "AGAPABCDEF"],
            ["prettyce", "dateformatym"],
            new(FrontMatter.EnsureSaddle, folders => WikiIndex.NotesWithoutSaddle(folders), "saddle-1", "saddle: saddle-1"),
            new(FrontMatter.EnsurePass, folders => WikiIndex.NotesWithoutPass(folders), "pass-1", "pass: pass-1"),
            "@startjungle\nApp\nCore\n@endjungle\n", ["App", "Core"], "aa0", "aa1", "junglepuml", "@startjungle",
            "---\nvectorbase: AGAP004707\nsaddle: saddle-1\npass: pass-1\n---\n# B\n", "---\nvectorbase: not-vectorbase\n---\n# N\n", "vectorbase IS VECTORBASE"),
        new("MaizeGdb_InfoPuml_PrettyAn_DateFormatY_And_Yaml", MarkdownEditing.LooksLikeMaizeGdb,
            ["GRMZM2G144761", "maizegdb:GRMZM2G144761", "https://www.maizegdb.org/gene_center/gene/GRMZM2G144761", "https://maizegdb.org/gene_center/gene/GRMZM2G144761"], ["not-maizegdb", "GRMZM", "GRMZM2GABCDEF"],
            ["prettyan", "dateformaty"],
            new(FrontMatter.EnsureTarn, folders => WikiIndex.NotesWithoutTarn(folders), "tarn-1", "tarn: tarn-1"),
            new(FrontMatter.EnsureFell, folders => WikiIndex.NotesWithoutFell(folders), "fell-1", "fell: fell-1"),
            "@startinfo\nApp\nCore\n@endinfo\n", ["App", "Core"], "ab0", "ab1", "infopuml", "@startinfo",
            "---\nmaizegdb: GRMZM2G144761\ntarn: tarn-1\nfell: fell-1\n---\n# B\n", "---\nmaizegdb: not-maizegdb\n---\n# N\n", "maizegdb IS MAIZEGDB"),
        new("SoyBase_EntityPuml_PrettyCname_DateFormatMd_And_Yaml", MarkdownEditing.LooksLikeSoyBase,
            ["Glyma.15G026400", "soybase:Glyma.15G026400", "https://www.soybase.org/gene/Glyma.15G026400", "https://soybase.org/gene/Glyma.15G026400"], ["not-soybase", "Glyma", "Glyma.15GABCDEF"],
            ["prettycname", "dateformatmd"],
            new(FrontMatter.EnsureCombe, folders => WikiIndex.NotesWithoutCombe(folders), "combe-1", "combe: combe-1"),
            new(FrontMatter.EnsureDale, folders => WikiIndex.NotesWithoutDale(folders), "dale-1", "dale: dale-1"),
            "@startentity\nApp\nCore\n@endentity\n", ["App", "Core"], "ac0", "ac1", "entitypuml", "@startentity",
            "---\nsoybase: Glyma.15G026400\ncombe: combe-1\ndale: dale-1\n---\n# B\n", "---\nsoybase: not-soybase\n---\n# N\n", "soybase IS SOYBASE"),
        new("Gramene_SudokuPuml_PrettyAemail_DateFormatHm_And_Yaml", MarkdownEditing.LooksLikeGramene,
            ["Os01g0100100", "gramene:Os01g0100100", "https://www.gramene.org/gene/Os01g0100100", "https://gramene.org/gene/Os01g0100100"], ["not-gramene", "Os", "Os01gABCDEFG"],
            ["prettyaemail", "dateformathm"],
            new(FrontMatter.EnsureKame, folders => WikiIndex.NotesWithoutKame(folders), "kame-1", "kame: kame-1"),
            new(FrontMatter.EnsureEsker, folders => WikiIndex.NotesWithoutEsker(folders), "esker-1", "esker: esker-1"),
            "@startsudoku\nApp\nCore\n@endsudoku\n", ["App", "Core"], "ad0", "ad1", "sudokupuml", "@startsudoku",
            "---\ngramene: Os01g0100100\nkame: kame-1\nesker: esker-1\n---\n# B\n", "---\ngramene: not-gramene\n---\n# N\n", "gramene IS GRAMENE"),
        new("Phytozome_PackagePuml_PrettyCemail_DateFormatHms_And_Yaml", MarkdownEditing.LooksLikePhytozome,
            ["Potri.001G004000", "phytozome:Potri.001G004000", "https://www.phytozome.net/gene/Potri.001G004000", "https://phytozome.net/gene/Potri.001G004000"], ["not-phytozome", "Potri", "Potri.001GABCDEF"],
            ["prettycemail", "dateformathms"],
            new(FrontMatter.EnsureDrumlin, folders => WikiIndex.NotesWithoutDrumlin(folders), "drumlin-1", "drumlin: drumlin-1"),
            new(FrontMatter.EnsureErratic, folders => WikiIndex.NotesWithoutErratic(folders), "erratic-1", "erratic: erratic-1"),
            "@startpackage\nApp\nCore\n@endpackage\n", ["App", "Core"], "ae0", "ae1", "packagepuml", "@startpackage",
            "---\nphytozome: Potri.001G004000\ndrumlin: drumlin-1\nerratic: erratic-1\n---\n# B\n", "---\nphytozome: not-phytozome\n---\n# N\n", "phytozome IS PHYTOZOME"),
        new("Jgi_FolderPuml_PrettyAname_DateFormatA_And_Yaml", MarkdownEditing.LooksLikeJgi,
            ["Ga00001234", "jgi:Ga00001234", "https://www.jgi.doe.gov/gene/Ga00001234", "https://jgi.doe.gov/gene/Ga00001234"], ["not-jgi", "Ga", "GaABCDEFGH"],
            ["prettyaname", "dateformata"],
            new(FrontMatter.EnsureLoess, folders => WikiIndex.NotesWithoutLoess(folders), "loess-1", "loess: loess-1"),
            new(FrontMatter.EnsureTill, folders => WikiIndex.NotesWithoutTill(folders), "till-1", "till: till-1"),
            "@startfolder\nApp\nCore\n@endfolder\n", ["App", "Core"], "af0", "af1", "folderpuml", "@startfolder",
            "---\njgi: Ga00001234\nloess: loess-1\ntill: till-1\n---\n# B\n", "---\njgi: not-jgi\n---\n# N\n", "jgi IS JGI"),
        new("Hp_FramePuml_PrettyBody_DateFormatWd_And_Yaml", MarkdownEditing.LooksLikeHp,
            ["HP:0000001", "hp:0000001", "https://www.hpo.jax.org/app/browse/term/HP:0000001", "https://hpo.jax.org/app/browse/term/HP:0000001"], ["not-hp", "HP", "HP:ABCDEFG"],
            ["prettybody", "dateformatwd"],
            new(FrontMatter.EnsureVarve, folders => WikiIndex.NotesWithoutVarve(folders), "varve-1", "varve: varve-1"),
            new(FrontMatter.EnsureOutwash, folders => WikiIndex.NotesWithoutOutwash(folders), "outwash-1", "outwash: outwash-1"),
            "@startframe\nApp\nCore\n@endframe\n", ["App", "Core"], "ag0", "ag1", "framepuml", "@startframe",
            "---\nhp: HP:0000001\nvarve: varve-1\noutwash: outwash-1\n---\n# B\n", "---\nhp: not-hp\n---\n# N\n", "hp IS HP"),
        new("Mondo_CloudPuml_PrettyF_DateFormatMon_And_Yaml", MarkdownEditing.LooksLikeMondo,
            ["MONDO:0000001", "mondo:0000001", "https://www.monarchinitiative.org/disease/MONDO:0000001", "https://monarchinitiative.org/disease/MONDO:0000001"], ["not-mondo", "MONDO", "MONDO:ABCDEFG"],
            ["prettyf", "dateformatmon"],
            new(FrontMatter.EnsureKettle, folders => WikiIndex.NotesWithoutKettle(folders), "kettle-1", "kettle: kettle-1"),
            new(FrontMatter.EnsurePingo, folders => WikiIndex.NotesWithoutPingo(folders), "pingo-1", "pingo: pingo-1"),
            "@startcloud\nApp\nCore\n@endcloud\n", ["App", "Core"], "ah0", "ah1", "cloudpuml", "@startcloud",
            "---\nmondo: MONDO:0000001\nkettle: kettle-1\npingo: pingo-1\n---\n# B\n", "---\nmondo: not-mondo\n---\n# N\n", "mondo IS MONDO"),
        new("Doid_NodePuml_PrettyD_DateFormatM_And_Yaml", MarkdownEditing.LooksLikeDoid,
            ["DOID:0000001", "doid:0000001", "https://www.disease-ontology.org/term/DOID:0000001", "https://disease-ontology.org/term/DOID:0000001"], ["not-doid", "DOID", "DOID:ABCDEFG"],
            ["prettyd", "dateformatm"],
            new(FrontMatter.EnsurePalsa, folders => WikiIndex.NotesWithoutPalsa(folders), "palsa-1", "palsa: palsa-1"),
            new(FrontMatter.EnsureLithalsa, folders => WikiIndex.NotesWithoutLithalsa(folders), "lithalsa-1", "lithalsa: lithalsa-1"),
            "@startnode\nApp\nCore\n@endnode\n", ["App", "Core"], "ai0", "ai1", "nodepuml", "@startnode",
            "---\ndoid: DOID:0000001\npalsa: palsa-1\nlithalsa: lithalsa-1\n---\n# B\n", "---\ndoid: not-doid\n---\n# N\n", "doid IS DOID"),
        new("Uberon_QueuePuml_PrettyT_DateFormatD_And_Yaml", MarkdownEditing.LooksLikeUberon,
            ["UBERON:0000001", "uberon:0000001", "https://www.ebi.ac.uk/ols4/ontologies/uberon/terms?obo_id=UBERON:0000001", "https://www.ebi.ac.uk/ols/ontologies/uberon/terms?obo_id=UBERON:0000001"], ["not-uberon", "UBERON", "UBERON:ABCDEFG"],
            ["prettyt", "dateformatd"],
            new(FrontMatter.EnsureTalik, folders => WikiIndex.NotesWithoutTalik(folders), "talik-1", "talik: talik-1"),
            new(FrontMatter.EnsureAlass, folders => WikiIndex.NotesWithoutAlass(folders), "alass-1", "alass: alass-1"),
            "@startqueue\nApp\nCore\n@endqueue\n", ["App", "Core"], "aj0", "aj1", "queuepuml", "@startqueue",
            "---\nuberon: UBERON:0000001\ntalik: talik-1\nalass: alass-1\n---\n# B\n", "---\nuberon: not-uberon\n---\n# N\n", "uberon IS UBERON"),
        new("Efo_DatabasePuml_PrettyP_DateFormatH_And_Yaml", MarkdownEditing.LooksLikeEfo,
            ["EFO:0000001", "efo:0000001", "https://www.ebi.ac.uk/ols4/ontologies/efo/terms?obo_id=EFO:0000001", "https://www.ebi.ac.uk/ols/ontologies/efo/terms?obo_id=EFO:0000001"], ["not-efo", "EFO", "EFO:ABCDEFG"],
            ["prettyp", "dateformath"],
            new(FrontMatter.EnsureNaled, folders => WikiIndex.NotesWithoutNaled(folders), "naled-1", "naled: naled-1"),
            new(FrontMatter.EnsureAufeis, folders => WikiIndex.NotesWithoutAufeis(folders), "aufeis-1", "aufeis: aufeis-1"),
            "@startdatabase\nApp\nCore\n@enddatabase\n", ["App", "Core"], "ak0", "ak1", "databasepuml", "@startdatabase",
            "---\nefo: EFO:0000001\nnaled: naled-1\naufeis: aufeis-1\n---\n# B\n", "---\nefo: not-efo\n---\n# N\n", "efo IS EFO"),
        new("Ncit_RectanglePuml_PrettyGd_DateFormatI_And_Yaml", MarkdownEditing.LooksLikeNcit,
            ["NCIT:C0000001", "ncit:C0000001", "https://www.ebi.ac.uk/ols4/ontologies/ncit/terms?obo_id=NCIT:C0000001", "https://www.ebi.ac.uk/ols/ontologies/ncit/terms?obo_id=NCIT:C0000001"], ["not-ncit", "NCIT", "NCIT:ABCDEFG"],
            ["prettygd", "dateformati"],
            new(FrontMatter.EnsurePolynya, folders => WikiIndex.NotesWithoutPolynya(folders), "polynya-1", "polynya: polynya-1"),
            new(FrontMatter.EnsureFrazil, folders => WikiIndex.NotesWithoutFrazil(folders), "frazil-1", "frazil: frazil-1"),
            "@startrectangle\nApp\nCore\n@endrectangle\n", ["App", "Core"], "al0", "al1", "rectanglepuml", "@startrectangle",
            "---\nncit: NCIT:C0000001\npolynya: polynya-1\nfrazil: frazil-1\n---\n# B\n", "---\nncit: not-ncit\n---\n# N\n", "ncit IS NCIT"),
        new("Cl_StoragePuml_PrettyGn_DateFormatMin_And_Yaml", MarkdownEditing.LooksLikeCl,
            ["CL:0000001", "cl:0000001", "https://www.ebi.ac.uk/ols4/ontologies/cl/terms?obo_id=CL:0000001", "https://www.ebi.ac.uk/ols/ontologies/cl/terms?obo_id=CL:0000001"], ["not-cl", "CL", "CL:ABCDEFG"],
            ["prettygn", "dateformatmin"],
            new(FrontMatter.EnsureSastrugi, folders => WikiIndex.NotesWithoutSastrugi(folders), "sastrugi-1", "sastrugi: sastrugi-1"),
            new(FrontMatter.EnsureZastruga, folders => WikiIndex.NotesWithoutZastruga(folders), "zastruga-1", "zastruga: zastruga-1"),
            "@startstorage\nApp\nCore\n@endstorage\n", ["App", "Core"], "am0", "am1", "storagepuml", "@startstorage",
            "---\ncl: CL:0000001\nsastrugi: sastrugi-1\nzastruga: zastruga-1\n---\n# B\n", "---\ncl: not-cl\n---\n# N\n", "cl IS CL"),
        new("Pr_CardPuml_PrettyGs_DateFormatS_And_Yaml", MarkdownEditing.LooksLikePr,
            ["PR:000000001", "pr:000000001", "https://www.ebi.ac.uk/ols4/ontologies/pr/terms?obo_id=PR:000000001", "https://www.ebi.ac.uk/ols/ontologies/pr/terms?obo_id=PR:000000001"], ["not-pr", "PR", "PR:ABCDEFG"],
            ["prettygs", "dateformats"],
            new(FrontMatter.EnsurePenitente, folders => WikiIndex.NotesWithoutPenitente(folders), "penitente-1", "penitente: penitente-1"),
            new(FrontMatter.EnsureRime, folders => WikiIndex.NotesWithoutRime(folders), "rime-1", "rime: rime-1"),
            "@startcard\nApp\nCore\n@endcard\n", ["App", "Core"], "an0", "an1", "cardpuml", "@startcard",
            "---\npr: PR:000000001\npenitente: penitente-1\nrime: rime-1\n---\n# B\n", "---\npr: not-pr\n---\n# N\n", "pr IS PR"),
        new("So_StackPuml_PrettyGe_DateFormatT_And_Yaml", MarkdownEditing.LooksLikeSo,
            ["SO:0000001", "so:0000001", "https://www.ebi.ac.uk/ols4/ontologies/so/terms?obo_id=SO:0000001", "https://www.ebi.ac.uk/ols/ontologies/so/terms?obo_id=SO:0000001"], ["not-so", "SO", "SO:ABCDEFG"],
            ["prettyge", "dateformatt"],
            new(FrontMatter.EnsureGraupel, folders => WikiIndex.NotesWithoutGraupel(folders), "graupel-1", "graupel: graupel-1"),
            new(FrontMatter.EnsureHoar, folders => WikiIndex.NotesWithoutHoar(folders), "hoar-1", "hoar: hoar-1"),
            "@startstack\nApp\nCore\n@endstack\n", ["App", "Core"], "ao0", "ao1", "stackpuml", "@startstack",
            "---\nso: SO:0000001\ngraupel: graupel-1\nhoar: hoar-1\n---\n# B\n", "---\nso: not-so\n---\n# N\n", "so IS SO"),
        new("Obi_ArtifactPuml_PrettyCi_DateFormatR_And_Yaml", MarkdownEditing.LooksLikeObi,
            ["OBI:0000001", "obi:0000001", "https://www.ebi.ac.uk/ols4/ontologies/obi/terms?obo_id=OBI:0000001", "https://www.ebi.ac.uk/ols/ontologies/obi/terms?obo_id=OBI:0000001"], ["not-obi", "OBI", "OBI:ABCDEFG"],
            ["prettyci", "dateformatr"],
            new(FrontMatter.EnsureCornice, folders => WikiIndex.NotesWithoutCornice(folders), "cornice-1", "cornice: cornice-1"),
            new(FrontMatter.EnsureSlab, folders => WikiIndex.NotesWithoutSlab(folders), "slab-1", "slab: slab-1"),
            "@startartifact\nApp\nCore\n@endartifact\n", ["App", "Core"], "ap0", "ap1", "artifactpuml", "@startartifact",
            "---\nobi: OBI:0000001\ncornice: cornice-1\nslab: slab-1\n---\n# B\n", "---\nobi: not-obi\n---\n# N\n", "obi IS OBI"),
        new("Envo_HexagonPuml_PrettyCd_DateFormatF_And_Yaml", MarkdownEditing.LooksLikeEnvo,
            ["ENVO:00000001", "envo:00000001", "https://www.ebi.ac.uk/ols4/ontologies/envo/terms?obo_id=ENVO:00000001", "https://www.ebi.ac.uk/ols/ontologies/envo/terms?obo_id=ENVO:00000001"], ["not-envo", "ENVO", "ENVO:ABCDEFG"],
            ["prettycd", "dateformatf"],
            new(FrontMatter.EnsureBarchan, folders => WikiIndex.NotesWithoutBarchan(folders), "barchan-1", "barchan: barchan-1"),
            new(FrontMatter.EnsureSeif, folders => WikiIndex.NotesWithoutSeif(folders), "seif-1", "seif: seif-1"),
            "@starthexagon\nApp\nCore\n@endhexagon\n", ["App", "Core"], "aq0", "aq1", "hexagonpuml", "@starthexagon",
            "---\nenvo: ENVO:00000001\nbarchan: barchan-1\nseif: seif-1\n---\n# B\n", "---\nenvo: not-envo\n---\n# N\n", "envo IS ENVO"),
        new("Pato_BoundaryPuml_PrettyCr_DateFormatZ_And_Yaml", MarkdownEditing.LooksLikePato,
            ["PATO:0000001", "pato:0000001", "https://www.ebi.ac.uk/ols4/ontologies/pato/terms?obo_id=PATO:0000001", "https://www.ebi.ac.uk/ols/ontologies/pato/terms?obo_id=PATO:0000001"], ["not-pato", "PATO", "PATO:ABCDEFG"],
            ["prettycr", "dateformatz"],
            new(FrontMatter.EnsureYardang, folders => WikiIndex.NotesWithoutYardang(folders), "yardang-1", "yardang: yardang-1"),
            new(FrontMatter.EnsureErg, folders => WikiIndex.NotesWithoutErg(folders), "erg-1", "erg: erg-1"),
            "@startboundary\nApp\nCore\n@endboundary\n", ["App", "Core"], "ar0", "ar1", "boundarypuml", "@startboundary",
            "---\npato: PATO:0000001\nyardang: yardang-1\nerg: erg-1\n---\n# B\n", "---\npato: not-pato\n---\n# N\n", "pato IS PATO"),
        new("Po_ControlPuml_PrettyCt_DateFormatX_And_Yaml", MarkdownEditing.LooksLikePo,
            ["PO:0000001", "po:0000001", "https://www.ebi.ac.uk/ols4/ontologies/po/terms?obo_id=PO:0000001", "https://www.ebi.ac.uk/ols/ontologies/po/terms?obo_id=PO:0000001"], ["not-po", "PO", "PO:ABCDEFG"],
            ["prettyct", "dateformatx"],
            new(FrontMatter.EnsureDraa, folders => WikiIndex.NotesWithoutDraa(folders), "draa-1", "draa: draa-1"),
            new(FrontMatter.EnsureHamada, folders => WikiIndex.NotesWithoutHamada(folders), "hamada-1", "hamada: hamada-1"),
            "@startcontrol\nApp\nCore\n@endcontrol\n", ["App", "Core"], "as0", "as1", "controlpuml", "@startcontrol",
            "---\npo: PO:0000001\ndraa: draa-1\nhamada: hamada-1\n---\n# B\n", "---\npo: not-po\n---\n# N\n", "po IS PO"),
        new("Fma_InterfacePuml_PrettyAd_DateFormatP_And_Yaml", MarkdownEditing.LooksLikeFma,
            ["FMA:12345", "fma:12345", "https://www.ebi.ac.uk/ols4/ontologies/fma/terms?obo_id=FMA:12345", "https://www.ebi.ac.uk/ols/ontologies/fma/terms?obo_id=FMA:12345"], ["not-fma", "FMA", "FMA:ABCDEFG"],
            ["prettyad", "dateformatp"],
            new(FrontMatter.EnsureQanat, folders => WikiIndex.NotesWithoutQanat(folders), "qanat-1", "qanat: qanat-1"),
            new(FrontMatter.EnsureWadi, folders => WikiIndex.NotesWithoutWadi(folders), "wadi-1", "wadi: wadi-1"),
            "@startinterface\nApp\nCore\n@endinterface\n", ["App", "Core"], "at0", "at1", "interfacepuml", "@startinterface",
            "---\nfma: FMA:12345\nqanat: qanat-1\nwadi: wadi-1\n---\n# B\n", "---\nfma: not-fma\n---\n# N\n", "fma IS FMA"),
        new("Foodon_ActorPuml_PrettyAt_DateFormatJ_And_Yaml", MarkdownEditing.LooksLikeFoodon,
            ["FOODON:00002403", "foodon:00002403", "https://www.ebi.ac.uk/ols4/ontologies/foodon/terms?obo_id=FOODON:00002403", "https://www.ebi.ac.uk/ols/ontologies/foodon/terms?obo_id=FOODON:00002403"], ["not-foodon", "FOODON", "FOODON:ABCDEFG"],
            ["prettyat", "dateformatj"],
            new(FrontMatter.EnsureSabkha, folders => WikiIndex.NotesWithoutSabkha(folders), "sabkha-1", "sabkha: sabkha-1"),
            new(FrontMatter.EnsurePlaya, folders => WikiIndex.NotesWithoutPlaya(folders), "playa-1", "playa: playa-1"),
            "@startactor\nApp\nCore\n@endactor\n", ["App", "Core"], "au0", "au1", "actorpuml", "@startactor",
            "---\nfoodon: FOODON:00002403\nsabkha: sabkha-1\nplaya: playa-1\n---\n# B\n", "---\nfoodon: not-foodon\n---\n# N\n", "foodon IS FOODON"),
        new("Fypo_AgentPuml_PrettyAi_DateFormatU_And_Yaml", MarkdownEditing.LooksLikeFypo,
            ["FYPO:0000001", "fypo:0000001", "https://www.ebi.ac.uk/ols4/ontologies/fypo/terms?obo_id=FYPO:0000001", "https://www.ebi.ac.uk/ols/ontologies/fypo/terms?obo_id=FYPO:0000001"], ["not-fypo", "FYPO", "FYPO:ABCDEFG"],
            ["prettyai", "dateformatu"],
            new(FrontMatter.EnsureCaliche, folders => WikiIndex.NotesWithoutCaliche(folders), "caliche-1", "caliche: caliche-1"),
            new(FrontMatter.EnsureSerir, folders => WikiIndex.NotesWithoutSerir(folders), "serir-1", "serir: serir-1"),
            "@startagent\nApp\nCore\n@endagent\n", ["App", "Core"], "av0", "av1", "agentpuml", "@startagent",
            "---\nfypo: FYPO:0000001\ncaliche: caliche-1\nserir: serir-1\n---\n# B\n", "---\nfypo: not-fypo\n---\n# N\n", "fypo IS FYPO"),
        new("Nbo_LabelPuml_PrettyAs_DateFormatW_And_Yaml", MarkdownEditing.LooksLikeNbo,
            ["NBO:0000001", "nbo:0000001", "https://www.ebi.ac.uk/ols4/ontologies/nbo/terms?obo_id=NBO:0000001", "https://www.ebi.ac.uk/ols/ontologies/nbo/terms?obo_id=NBO:0000001"], ["not-nbo", "NBO", "NBO:ABCDEFG"],
            ["prettyas", "dateformatw"],
            new(FrontMatter.EnsureInselberg, folders => WikiIndex.NotesWithoutInselberg(folders), "inselberg-1", "inselberg: inselberg-1"),
            new(FrontMatter.EnsureBajada, folders => WikiIndex.NotesWithoutBajada(folders), "bajada-1", "bajada: bajada-1"),
            "@startlabel\nApp\nCore\n@endlabel\n", ["App", "Core"], "aw0", "aw1", "labelpuml", "@startlabel",
            "---\nnbo: NBO:0000001\ninselberg: inselberg-1\nbajada: bajada-1\n---\n# B\n", "---\nnbo: not-nbo\n---\n# N\n", "nbo IS NBO"),
        new("Chmo_PersonPuml_PrettyCs_DateFormatV_And_Yaml", MarkdownEditing.LooksLikeChmo,
            ["CHMO:0000001", "chmo:0000001", "https://www.ebi.ac.uk/ols4/ontologies/chmo/terms?obo_id=CHMO:0000001", "https://www.ebi.ac.uk/ols/ontologies/chmo/terms?obo_id=CHMO:0000001"], ["not-chmo", "CHMO", "CHMO:ABCDEFG"],
            ["prettycs", "dateformatv"],
            new(FrontMatter.EnsureOasis, folders => WikiIndex.NotesWithoutOasis(folders), "oasis-1", "oasis: oasis-1"),
            new(FrontMatter.EnsureDune, folders => WikiIndex.NotesWithoutDune(folders), "dune-1", "dune: dune-1"),
            "@startperson\nApp\nCore\n@endperson\n", ["App", "Core"], "ax0", "ax1", "personpuml", "@startperson",
            "---\nchmo: CHMO:0000001\noasis: oasis-1\ndune: dune-1\n---\n# B\n", "---\nchmo: not-chmo\n---\n# N\n", "chmo IS CHMO"),
        new("Mp_CirclePuml_PrettyN_DateFormatG_And_Yaml", MarkdownEditing.LooksLikeMp,
            ["MP:0000001", "mp:0000001", "https://www.ebi.ac.uk/ols4/ontologies/mp/terms?obo_id=MP:0000001", "https://www.ebi.ac.uk/ols/ontologies/mp/terms?obo_id=MP:0000001"], ["not-mp", "MP", "MP:ABCDEFG"],
            ["prettyn", "dateformatg"],
            new(FrontMatter.EnsurePediment, folders => WikiIndex.NotesWithoutPediment(folders), "pediment-1", "pediment: pediment-1"),
            new(FrontMatter.EnsureArroyo, folders => WikiIndex.NotesWithoutArroyo(folders), "arroyo-1", "arroyo: arroyo-1"),
            "@startcircle\nApp\nCore\n@endcircle\n", ["App", "Core"], "ay0", "ay1", "circlepuml", "@startcircle",
            "---\nmp: MP:0000001\npediment: pediment-1\narroyo: arroyo-1\n---\n# B\n", "---\nmp: not-mp\n---\n# N\n", "mp IS MP"),
        new("Zp_CollectionsPuml_PrettyE_DateFormatC_And_Yaml", MarkdownEditing.LooksLikeZp,
            ["ZP:0019030", "zp:0019030", "https://www.ebi.ac.uk/ols4/ontologies/zp/terms?obo_id=ZP:0019030", "https://www.ebi.ac.uk/ols/ontologies/zp/terms?obo_id=ZP:0019030"], ["not-zp", "ZP", "ZP:ABCDEFG"],
            ["prettye", "dateformatc"],
            new(FrontMatter.EnsureTanezrouft, folders => WikiIndex.NotesWithoutTanezrouft(folders), "tanezrouft-1", "tanezrouft: tanezrouft-1"),
            new(FrontMatter.EnsureAlluvial, folders => WikiIndex.NotesWithoutAlluvial(folders), "alluvial-1", "alluvial: alluvial-1"),
            "@startcollections\nApp\nCore\n@endcollections\n", ["App", "Core"], "az0", "az1", "collectionspuml", "@startcollections",
            "---\nzp: ZP:0019030\ntanezrouft: tanezrouft-1\nalluvial: alluvial-1\n---\n# B\n", "---\nzp: not-zp\n---\n# N\n", "zp IS ZP"),
        new("Maxo_TogetherPuml_PrettyTree_DateFormatWn_And_Yaml", MarkdownEditing.LooksLikeMaxo,
            ["MAXO:0001014", "maxo:0001014", "https://www.ebi.ac.uk/ols4/ontologies/maxo/terms?obo_id=MAXO:0001014", "https://www.ebi.ac.uk/ols/ontologies/maxo/terms?obo_id=MAXO:0001014"], ["not-maxo", "MAXO", "MAXO:ABCDEFG"],
            ["prettytree", "dateformatwn"],
            new(FrontMatter.EnsureGibber, folders => WikiIndex.NotesWithoutGibber(folders), "gibber-1", "gibber: gibber-1"),
            new(FrontMatter.EnsureVentifact, folders => WikiIndex.NotesWithoutVentifact(folders), "ventifact-1", "ventifact: ventifact-1"),
            "@starttogether\nApp\nCore\n@endtogether\n", ["App", "Core"], "ba0", "ba1", "togetherpuml", "@starttogether",
            "---\nmaxo: MAXO:0001014\ngibber: gibber-1\nventifact: ventifact-1\n---\n# B\n", "---\nmaxo: not-maxo\n---\n# N\n", "maxo IS MAXO"),
        new("Bfo_NotePuml_PrettyGk_DateFormatB_And_Yaml", MarkdownEditing.LooksLikeBfo,
            ["BFO:0000001", "bfo:0000001", "https://www.ebi.ac.uk/ols4/ontologies/bfo/terms?obo_id=BFO:0000001", "https://www.ebi.ac.uk/ols/ontologies/bfo/terms?obo_id=BFO:0000001"], ["not-bfo", "BFO", "BFO:ABCDEFG"],
            ["prettygk", "dateformatb"],
            new(FrontMatter.EnsureHoodoo, folders => WikiIndex.NotesWithoutHoodoo(folders), "hoodoo-1", "hoodoo: hoodoo-1"),
            new(FrontMatter.EnsureTephra, folders => WikiIndex.NotesWithoutTephra(folders), "tephra-1", "tephra: tephra-1"),
            "@startnote\nApp\nCore\n@endnote\n", ["App", "Core"], "bb0", "bb1", "notepuml", "@startnote",
            "---\nbfo: BFO:0000001\nhoodoo: hoodoo-1\ntephra: tephra-1\n---\n# B\n", "---\nbfo: not-bfo\n---\n# N\n", "bfo IS BFO"),
        new("Cmo_BoxPuml_PrettyGg_DateFormatK_And_Yaml", MarkdownEditing.LooksLikeCmo,
            ["CMO:0000001", "cmo:0000001", "https://www.ebi.ac.uk/ols4/ontologies/cmo/terms?obo_id=CMO:0000001", "https://www.ebi.ac.uk/ols/ontologies/cmo/terms?obo_id=CMO:0000001"], ["not-cmo", "CMO", "CMO:ABCDEFG"],
            ["prettygg", "dateformatk"],
            new(FrontMatter.EnsureLahar, folders => WikiIndex.NotesWithoutLahar(folders), "lahar-1", "lahar: lahar-1"),
            new(FrontMatter.EnsureCaldera, folders => WikiIndex.NotesWithoutCaldera(folders), "caldera-1", "caldera: caldera-1"),
            "@startbox\nApp\nCore\n@endbox\n", ["App", "Core"], "bc0", "bc1", "boxpuml", "@startbox",
            "---\ncmo: CMO:0000001\nlahar: lahar-1\ncaldera: caldera-1\n---\n# B\n", "---\ncmo: not-cmo\n---\n# N\n", "cmo IS CMO"),
        new("To_OvalPuml_PrettyGf_DateFormatE_And_Yaml", MarkdownEditing.LooksLikeTo,
            ["TO:0000387", "to:0000387", "https://www.ebi.ac.uk/ols4/ontologies/to/terms?obo_id=TO:0000387", "https://www.ebi.ac.uk/ols/ontologies/to/terms?obo_id=TO:0000387"], ["not-to", "TO", "TO:ABCDEFG"],
            ["prettygf", "dateformate"],
            new(FrontMatter.EnsureMaar, folders => WikiIndex.NotesWithoutMaar(folders), "maar-1", "maar: maar-1"),
            new(FrontMatter.EnsureIgnimbrite, folders => WikiIndex.NotesWithoutIgnimbrite(folders), "ignimbrite-1", "ignimbrite: ignimbrite-1"),
            "@startoval\nApp\nCore\n@endoval\n", ["App", "Core"], "bd0", "bd1", "ovalpuml", "@startoval",
            "---\nto: TO:0000387\nmaar: maar-1\nignimbrite: ignimbrite-1\n---\n# B\n", "---\nto: not-to\n---\n# N\n", "to IS TO"),
        new("Zfa_RoundedPuml_PrettyGt_DateFormatNs_And_Yaml", MarkdownEditing.LooksLikeZfa,
            ["ZFA:0000001", "zfa:0000001", "https://www.ebi.ac.uk/ols4/ontologies/zfa/terms?obo_id=ZFA:0000001", "https://www.ebi.ac.uk/ols/ontologies/zfa/terms?obo_id=ZFA:0000001"], ["not-zfa", "ZFA", "ZFA:ABCDEFG"],
            ["prettygt", "dateformatns"],
            new(FrontMatter.EnsureTumulus, folders => WikiIndex.NotesWithoutTumulus(folders), "tumulus-1", "tumulus: tumulus-1"),
            new(FrontMatter.EnsureScoria, folders => WikiIndex.NotesWithoutScoria(folders), "scoria-1", "scoria: scoria-1"),
            "@startrounded\nApp\nCore\n@endrounded\n", ["App", "Core"], "be0", "be1", "roundedpuml", "@startrounded",
            "---\nzfa: ZFA:0000001\ntumulus: tumulus-1\nscoria: scoria-1\n---\n# B\n", "---\nzfa: not-zfa\n---\n# N\n", "zfa IS ZFA"),
        new("Wbphenotype_HiddenPuml_PrettyGp_DateFormatLc_And_Yaml", MarkdownEditing.LooksLikeWbphenotype,
            ["WBPhenotype:0000001", "wbphenotype:0000001", "https://www.ebi.ac.uk/ols4/ontologies/wbphenotype/terms?obo_id=WBPhenotype:0000001", "https://www.ebi.ac.uk/ols/ontologies/wbphenotype/terms?obo_id=WBPhenotype:0000001"], ["not-wbphenotype", "WBPHENOTYPE", "WBPhenotype:ABCDEFG"],
            ["prettygp", "dateformatlc"],
            new(FrontMatter.EnsurePumice, folders => WikiIndex.NotesWithoutPumice(folders), "pumice-1", "pumice: pumice-1"),
            new(FrontMatter.EnsurePahoehoe, folders => WikiIndex.NotesWithoutPahoehoe(folders), "pahoehoe-1", "pahoehoe: pahoehoe-1"),
            "@starthidden\nApp\nCore\n@endhidden\n", ["App", "Core"], "bf0", "bf1", "hiddenpuml", "@starthidden",
            "---\nwbphenotype: WBPhenotype:0000001\npumice: pumice-1\npahoehoe: pahoehoe-1\n---\n# B\n", "---\nwbphenotype: not-wbphenotype\n---\n# N\n", "wbphenotype IS WBPHENOTYPE"),
        new("Xpo_PartitionPuml_PrettyCl_DateFormatTz_And_Yaml", MarkdownEditing.LooksLikeXpo,
            ["XPO:0000001", "xpo:0000001", "https://www.ebi.ac.uk/ols4/ontologies/xpo/terms?obo_id=XPO:0000001", "https://www.ebi.ac.uk/ols/ontologies/xpo/terms?obo_id=XPO:0000001"], ["not-xpo", "XPO", "XPO:ABCDEFG"],
            ["prettycl", "dateformattz"],
            new(FrontMatter.EnsurePillow, folders => WikiIndex.NotesWithoutPillow(folders), "pillow-1", "pillow: pillow-1"),
            new(FrontMatter.EnsureObsidian, folders => WikiIndex.NotesWithoutObsidian(folders), "obsidian-1", "obsidian: obsidian-1"),
            "@startpartition\nApp\nCore\n@endpartition\n", ["App", "Core"], "bg0", "bg1", "partitionpuml", "@startpartition",
            "---\nxpo: XPO:0000001\npillow: pillow-1\nobsidian: obsidian-1\n---\n# B\n", "---\nxpo: not-xpo\n---\n# N\n", "xpo IS XPO"),
        new("Xao_GroupPuml_PrettyAh_DateFormatLx_And_Yaml", MarkdownEditing.LooksLikeXao,
            ["XAO:0000001", "xao:0000001", "https://www.ebi.ac.uk/ols4/ontologies/xao/terms?obo_id=XAO:0000001", "https://www.ebi.ac.uk/ols/ontologies/xao/terms?obo_id=XAO:0000001"], ["not-xao", "XAO", "XAO:ABCDEFG"],
            ["prettyah", "dateformatlx"],
            new(FrontMatter.EnsureTuff, folders => WikiIndex.NotesWithoutTuff(folders), "tuff-1", "tuff: tuff-1"),
            new(FrontMatter.EnsureBasalt, folders => WikiIndex.NotesWithoutBasalt(folders), "basalt-1", "basalt: basalt-1"),
            "@startgroup\nApp\nCore\nendgroup\n", ["App", "Core"], "bh0", "bh1", "grouppuml", "@startgroup",
            "---\nxao: XAO:0000001\ntuff: tuff-1\nbasalt: basalt-1\n---\n# B\n", "---\nxao: not-xao\n---\n# N\n", "xao IS XAO"),
        new("Oba_ObjectPuml_PrettyCh_DateFormatEpoch_And_Yaml", MarkdownEditing.LooksLikeOba,
            ["OBA:0000001", "oba:0000001", "https://www.ebi.ac.uk/ols4/ontologies/oba/terms?obo_id=OBA:0000001", "https://www.ebi.ac.uk/ols/ontologies/oba/terms?obo_id=OBA:0000001"], ["not-oba", "OBA", "OBA:ABCDEFG"],
            ["prettych", "dateformatepoch"],
            new(FrontMatter.EnsureAndesite, folders => WikiIndex.NotesWithoutAndesite(folders), "andesite-1", "andesite: andesite-1"),
            new(FrontMatter.EnsureRhyolite, folders => WikiIndex.NotesWithoutRhyolite(folders), "rhyolite-1", "rhyolite: rhyolite-1"),
            "@startobject\nApp\nCore\n@endobject\n", ["App", "Core"], "bi0", "bi1", "objectpuml", "@startobject",
            "---\noba: OBA:0000001\nandesite: andesite-1\nrhyolite: rhyolite-1\n---\n# B\n", "---\noba: not-oba\n---\n# N\n", "oba IS OBA"),
        new("Rs_TreePuml_PrettyAl_DateFormatAmpm_And_Yaml", MarkdownEditing.LooksLikeRs,
            ["RS:0000001", "rs:0000001", "https://www.ebi.ac.uk/ols4/ontologies/rs/terms?obo_id=RS:0000001", "https://www.ebi.ac.uk/ols/ontologies/rs/terms?obo_id=RS:0000001"], ["not-rs", "RS", "RS:ABCDEFG"],
            ["prettyal", "dateformatampm"],
            new(FrontMatter.EnsureDacite, folders => WikiIndex.NotesWithoutDacite(folders), "dacite-1", "dacite: dacite-1"),
            new(FrontMatter.EnsurePhonolite, folders => WikiIndex.NotesWithoutPhonolite(folders), "phonolite-1", "phonolite: phonolite-1"),
            "@starttree\nApp\nCore\n@endtree\n", ["App", "Core"], "bj0", "bj1", "treepuml", "@starttree",
            "---\nrs: RS:0000001\ndacite: dacite-1\nphonolite: phonolite-1\n---\n# B\n", "---\nrs: not-rs\n---\n# N\n", "rs IS RS"),
        new("Wbbt_LegendPuml_PrettyAlm_DateFormatMdy_And_Yaml", MarkdownEditing.LooksLikeWbbt,
            ["WBbt:0000001", "wbbt:0000001", "https://www.ebi.ac.uk/ols4/ontologies/wbbt/terms?obo_id=WBbt:0000001", "https://www.ebi.ac.uk/ols/ontologies/wbbt/terms?obo_id=WBbt:0000001"], ["not-wbbt", "WBBT", "WBbt:ABCDEFG"],
            ["prettyalm", "dateformatmdy"],
            new(FrontMatter.EnsureXenolith, folders => WikiIndex.NotesWithoutXenolith(folders), "xenolith-1", "xenolith: xenolith-1"),
            new(FrontMatter.EnsureTrachyte, folders => WikiIndex.NotesWithoutTrachyte(folders), "trachyte-1", "trachyte: trachyte-1"),
            "@startlegend\nApp\nCore\n@endlegend\n", ["App", "Core"], "bk0", "bk1", "legendpuml", "@startlegend",
            "---\nwbbt: WBbt:0000001\nxenolith: xenolith-1\ntrachyte: trachyte-1\n---\n# B\n", "---\nwbbt: not-wbbt\n---\n# N\n", "wbbt IS WBBT"),
        new("Fbbt_LanePuml_PrettyClm_DateFormatAp_And_Yaml", MarkdownEditing.LooksLikeFbbt,
            ["FBbt:00000001", "fbbt:00000001", "https://www.ebi.ac.uk/ols4/ontologies/fbbt/terms?obo_id=FBbt:00000001", "https://www.ebi.ac.uk/ols/ontologies/fbbt/terms?obo_id=FBbt:00000001"], ["not-fbbt", "FBBT", "FBbt:ABCDEFGH"],
            ["prettyclm", "dateformatap"],
            new(FrontMatter.EnsureKimberlite, folders => WikiIndex.NotesWithoutKimberlite(folders), "kimberlite-1", "kimberlite: kimberlite-1"),
            new(FrontMatter.EnsureCarbonatite, folders => WikiIndex.NotesWithoutCarbonatite(folders), "carbonatite-1", "carbonatite: carbonatite-1"),
            "@startlane\nApp\nCore\nendlane\n", ["App", "Core"], "bl0", "bl1", "lanepuml", "@startlane",
            "---\nfbbt: FBbt:00000001\nkimberlite: kimberlite-1\ncarbonatite: carbonatite-1\n---\n# B\n", "---\nfbbt: not-fbbt\n---\n# N\n", "fbbt IS FBBT"),
        new("Fbcv_SwimPuml_PrettyGsigner_DateFormatWeekday_And_Yaml", MarkdownEditing.LooksLikeFbcv,
            ["FBcv:0000001", "fbcv:0000001", "https://www.ebi.ac.uk/ols4/ontologies/fbcv/terms?obo_id=FBcv:0000001", "https://www.ebi.ac.uk/ols/ontologies/fbcv/terms?obo_id=FBcv:0000001"], ["not-fbcv", "FBCV", "FBcv:ABCDEFG"],
            ["prettygsigner", "dateformatweekday"],
            new(FrontMatter.EnsureSchist, folders => WikiIndex.NotesWithoutSchist(folders), "schist-1", "schist: schist-1"),
            new(FrontMatter.EnsureGneiss, folders => WikiIndex.NotesWithoutGneiss(folders), "gneiss-1", "gneiss: gneiss-1"),
            "@startswim\nApp\nCore\nendswim\n", ["App", "Core"], "bm0", "bm1", "swimpuml", "@startswim",
            "---\nfbcv: FBcv:0000001\nschist: schist-1\ngneiss: gneiss-1\n---\n# B\n", "---\nfbcv: not-fbcv\n---\n# N\n", "fbcv IS FBCV"),
        new("Fbdv_HeaderPuml_PrettyGstatus_DateFormatYy_And_Yaml", MarkdownEditing.LooksLikeFbdv,
            ["FBdv:00000001", "fbdv:00000001", "https://www.ebi.ac.uk/ols4/ontologies/fbdv/terms?obo_id=FBdv:00000001", "https://www.ebi.ac.uk/ols/ontologies/fbdv/terms?obo_id=FBdv:00000001"], ["not-fbdv", "FBDV", "FBdv:ABCDEFGH"],
            ["prettygstatus", "dateformatyy"],
            new(FrontMatter.EnsureMarble, folders => WikiIndex.NotesWithoutMarble(folders), "marble-1", "marble: marble-1"),
            new(FrontMatter.EnsureQuartzite, folders => WikiIndex.NotesWithoutQuartzite(folders), "quartzite-1", "quartzite: quartzite-1"),
            "@startheader\nApp\nCore\nendheader\n", ["App", "Core"], "bn0", "bn1", "headerpuml", "@startheader",
            "---\nfbdv: FBdv:00000001\nmarble: marble-1\nquartzite: quartzite-1\n---\n# B\n", "---\nfbdv: not-fbdv\n---\n# N\n", "fbdv IS FBDV"),
        new("Fbbi_FooterPuml_PrettyGhash_DateFormatUsweek_And_Yaml", MarkdownEditing.LooksLikeFbbi,
            ["FBbi:00000001", "fbbi:00000001", "https://www.ebi.ac.uk/ols4/ontologies/fbbi/terms?obo_id=FBbi:00000001", "https://www.ebi.ac.uk/ols/ontologies/fbbi/terms?obo_id=FBbi:00000001"], ["not-fbbi", "FBBI", "FBbi:ABCDEFGH"],
            ["prettyghash", "dateformatusweek"],
            new(FrontMatter.EnsureSlate, folders => WikiIndex.NotesWithoutSlate(folders), "slate-1", "slate: slate-1"),
            new(FrontMatter.EnsurePhyllite, folders => WikiIndex.NotesWithoutPhyllite(folders), "phyllite-1", "phyllite: phyllite-1"),
            "@startfooter\nApp\nCore\nendfooter\n", ["App", "Core"], "bo0", "bo1", "footerpuml", "@startfooter",
            "---\nfbbi: FBbi:00000001\nslate: slate-1\nphyllite: phyllite-1\n---\n# B\n", "---\nfbbi: not-fbbi\n---\n# N\n", "fbbi IS FBBI"),
        new("Fbhh_TitlePuml_PrettyGlocal_DateFormatTwelve_And_Yaml", MarkdownEditing.LooksLikeFbhh,
            ["FBhh:0000001", "fbhh:0000001", "https://www.ebi.ac.uk/ols4/ontologies/fbhh/terms?obo_id=FBhh:0000001", "https://www.ebi.ac.uk/ols/ontologies/fbhh/terms?obo_id=FBhh:0000001"], ["not-fbhh", "FBHH", "FBhh:ABCDEFG"],
            ["prettyglocal", "dateformattwelve"],
            new(FrontMatter.EnsureAmphibolite, folders => WikiIndex.NotesWithoutAmphibolite(folders), "amphibolite-1", "amphibolite: amphibolite-1"),
            new(FrontMatter.EnsureEclogite, folders => WikiIndex.NotesWithoutEclogite(folders), "eclogite-1", "eclogite: eclogite-1"),
            "@starttitle\nApp\nCore\nendtitle\n", ["App", "Core"], "bp0", "bp1", "titlepuml", "@starttitle",
            "---\nfbhh: FBhh:0000001\namphibolite: amphibolite-1\neclogite: eclogite-1\n---\n# B\n", "---\nfbhh: not-fbhh\n---\n# N\n", "fbhh IS FBHH"),
        new("Fbsp_CaptionPuml_PrettyGnm_DateFormatPlus_And_Yaml", MarkdownEditing.LooksLikeFbsp,
            ["FBsp:00000001", "fbsp:00000001", "https://www.ebi.ac.uk/ols4/ontologies/fbsp/terms?obo_id=FBsp:00000001", "https://www.ebi.ac.uk/ols/ontologies/fbsp/terms?obo_id=FBsp:00000001"], ["not-fbsp", "FBSP", "FBsp:ABCDEFGH"],
            ["prettygnm", "dateformatplus"],
            new(FrontMatter.EnsureGranulite, folders => WikiIndex.NotesWithoutGranulite(folders), "granulite-1", "granulite: granulite-1"),
            new(FrontMatter.EnsureMigmatite, folders => WikiIndex.NotesWithoutMigmatite(folders), "migmatite-1", "migmatite: migmatite-1"),
            "@startcaption\nApp\nCore\nendcaption\n", ["App", "Core"], "bq0", "bq1", "captionpuml", "@startcaption",
            "---\nfbsp: FBsp:00000001\ngranulite: granulite-1\nmigmatite: migmatite-1\n---\n# B\n", "---\nfbsp: not-fbsp\n---\n# N\n", "fbsp IS FBSP"),
        new("Bto_NewpagePuml_PrettyM_DateFormatN_And_Yaml", MarkdownEditing.LooksLikeBto,
            ["BTO:0000001", "bto:0000001", "https://www.ebi.ac.uk/ols4/ontologies/bto/terms?obo_id=BTO:0000001", "https://www.ebi.ac.uk/ols/ontologies/bto/terms?obo_id=BTO:0000001"], ["not-bto", "BTO", "BTO:ABCDEFG"],
            ["prettym", "dateformatn"],
            new(FrontMatter.EnsureHornfels, folders => WikiIndex.NotesWithoutHornfels(folders), "hornfels-1", "hornfels: hornfels-1"),
            new(FrontMatter.EnsureSkarn, folders => WikiIndex.NotesWithoutSkarn(folders), "skarn-1", "skarn: skarn-1"),
            "@startnewpage\nApp\nCore\nendnewpage\n", ["App", "Core"], "br0", "br1", "newpagepuml", "@startnewpage",
            "---\nbto: BTO:0000001\nhornfels: hornfels-1\nskarn: skarn-1\n---\n# B\n", "---\nbto: not-bto\n---\n# N\n", "bto IS BTO"),
    ];
}
